### Project Chicago: Transform ResStock PACKAGE Results for paper to 15 SFD prototypes (Elevate Energy)
Created on: 01/07/2020 \
By: Lixi Liu (Lixi.Liu@nrel.gov)

In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
print(f'Notebook path: {os.getcwd()}')

Notebook path: /Users/lliu2/Documents/GitHub/ResStock/files

### Download results online
* unprocessed upgrade results: S3/resbldg-datasets/chicagoeui
* processed result tables for plots: https://nrel.sharepoint.com/sites/ChicagoRetrofits/Shared%20Documents/Forms/AllItems.aspx?viewid=289cdd1a%2D97c9%2D4bcc%2D8416%2Dc19bf01c6302&id=%2Fsites%2FChicagoRetrofits%2FShared%20Documents%2FGeneral%2FUpgrade%20results

### Initialize
For modifying plots, can go directly to section 2.3 after initialization

In [6]:
# local path to downloaded results
iteration = 'paper_all'
iter_path = f'cookcnty_packages_{iteration}'
result_dir = '/Users/lliu2/Documents/Chicago retrofits/ResStock results'
result_path = os.path.join(result_dir, iter_path)

## create folder for post-processed results:
if not os.path.exists(os.path.join(result_path, 'processed results')):
    os.mkdir(os.path.join(result_path, 'processed results'))
    
## create folder for exported baseline and upgrade results to csv (to share with Elevate):
combined_res_csv_path = os.path.join(result_path, 'processed results', 'processed csvs')
if not os.path.exists(combined_res_csv_path):
    os.mkdir(combined_res_csv_path)
    
## create folder for plots:
plot_path = os.path.join(result_path, 'processed results', 'plots')
if not os.path.exists(plot_path):
    os.mkdir(plot_path)

print(f'Results path: \n   {result_path}')

Results path:
   /Users/lliu2/Documents/Chicago retrofits/ResStock results/cookcnty_packages_paper_all

In [27]:
f = pd.read_csv("/Users/lliu2/Documents/Chicago retrofits/ResStock results/cookcnty_packages_paper_all/processed results/upgrades_dB.csv")
f

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,simulation_output_report.applicable,simulation_output_report.door_area_ft_2,...,ann_elec_cost_saving,ann_energy_cost_saving,ann_kbtu_saved_per_dollar,simple_payback,ann_metric_ton_co2e_saving_gas,ann_metric_ton_co2e_saving_elec,ann_metric_ton_co2e_saving,package_no,HousingGroupNo,HousingGroupName
0,1,44,2021-08-07 10:12:15,2021-08-07 10:20:33,Success,True,Full Upgrade (Electrification),NaN,True,20.000000,...,-157.950106,1012.550688,3.489277,25.809246,5.409696,-2.554240,2.855456,10.0,4.0,Masonry 1942-1978 Less than 2 Stories
1,1,144,2021-08-07 06:21:27,2021-08-07 06:28:44,Success,True,Electrification with HP Deep Efficiency,NaN,True,20.000000,...,-451.794758,718.706036,4.126118,27.596958,5.409696,-4.841023,0.568673,8.0,4.0,Masonry 1942-1978 Less than 2 Stories
2,1,123,2021-08-07 09:25:10,2021-08-07 09:30:18,Success,True,HP HVAC with Premium Shell,NaN,True,20.000000,...,-46.805465,352.741912,4.270289,42.176049,3.449123,-0.309561,3.139562,3.0,4.0,Masonry 1942-1978 Less than 2 Stories
3,1,88,2021-08-07 10:07:10,2021-08-07 10:11:35,Success,True,HP HVAC with Basic Shell,NaN,True,20.000000,...,-338.298362,63.468682,6.772666,130.299067,3.468284,-2.237428,1.230856,2.0,4.0,Masonry 1942-1978 Less than 2 Stories
4,1,92,2021-08-06 23:51:08,2021-08-06 23:54:31,Success,True,Utility Basic (Basic Shell),NaN,True,20.000000,...,94.597701,150.476082,4.026997,19.175140,0.482374,0.625648,1.108022,1.0,4.0,Masonry 1942-1978 Less than 2 Stories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439857,39996,196,2021-08-07 08:04:35,2021-08-07 08:06:03,Success,NaN,Baseline,NaN,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,Masonry Pre-1942 2 or more stories
439858,39997,43,2021-08-07 08:43:16,2021-08-07 08:44:45,Success,NaN,Baseline,NaN,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439859,39998,125,2021-08-07 06:17:39,2021-08-07 07:08:00,Success,NaN,Baseline,NaN,True,6.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439860,39999,17,2021-08-07 09:33:56,2021-08-07 09:35:37,Success,NaN,Baseline,NaN,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,Masonry Pre-1942 2 or more stories
439861,40000,139,2021-08-07 09:58:38,2021-08-07 10:00:13,Success,NaN,Baseline,NaN,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4.0,Masonry 1942-1978 Less than 2 Stories

In [28]:
f[f["apply_upgrade.upgrade_name"].isnull()]

Empty DataFrame
Columns: [building_id, job_id, started_at, completed_at, completed_status, apply_upgrade.applicable, apply_upgrade.upgrade_name, apply_upgrade.reference_scenario, simulation_output_report.applicable, simulation_output_report.door_area_ft_2, simulation_output_report.duct_surface_area_ft_2, simulation_output_report.electricity_bath_fan_kwh, simulation_output_report.electricity_ceiling_fan_kwh, simulation_output_report.electricity_central_system_cooling_kwh, simulation_output_report.electricity_central_system_heating_kwh, simulation_output_report.electricity_central_system_pumps_cooling_kwh, simulation_output_report.electricity_central_system_pumps_heating_kwh, simulation_output_report.electricity_clothes_dryer_kwh, simulation_output_report.electricity_clothes_washer_kwh, simulation_output_report.electricity_cooking_range_kwh, simulation_output_report.electricity_cooling_kwh, simulation_output_report.electricity_dishwasher_kwh, simulation_output_report.electricity_exterior_holiday_lighting_kwh, simulation_output_report.electricity_exterior_lighting_kwh, simulation_output_report.electricity_extra_refrigerator_kwh, simulation_output_report.electricity_fans_cooling_kwh, simulation_output_report.electricity_fans_heating_kwh, simulation_output_report.electricity_freezer_kwh, simulation_output_report.electricity_garage_lighting_kwh, simulation_output_report.electricity_heating_kwh, simulation_output_report.electricity_heating_supplemental_kwh, simulation_output_report.electricity_hot_tub_heater_kwh, simulation_output_report.electricity_hot_tub_pump_kwh, simulation_output_report.electricity_house_fan_kwh, simulation_output_report.electricity_interior_lighting_kwh, simulation_output_report.electricity_plug_loads_kwh, simulation_output_report.electricity_pool_heater_kwh, simulation_output_report.electricity_pool_pump_kwh, simulation_output_report.electricity_pumps_cooling_kwh, simulation_output_report.electricity_pumps_heating_kwh, simulation_output_report.electricity_pv_kwh, simulation_output_report.electricity_range_fan_kwh, simulation_output_report.electricity_recirc_pump_kwh, simulation_output_report.electricity_refrigerator_kwh, simulation_output_report.electricity_vehicle_kwh, simulation_output_report.electricity_water_systems_kwh, simulation_output_report.electricity_well_pump_kwh, simulation_output_report.floor_area_attic_ft_2, simulation_output_report.floor_area_conditioned_ft_2, simulation_output_report.floor_area_lighting_ft_2, simulation_output_report.fuel_oil_central_system_heating_mbtu, simulation_output_report.fuel_oil_heating_mbtu, simulation_output_report.fuel_oil_water_systems_mbtu, simulation_output_report.hours_cooling_setpoint_not_met, simulation_output_report.hours_heating_setpoint_not_met, simulation_output_report.hvac_cooling_capacity_w, simulation_output_report.hvac_heating_capacity_w, simulation_output_report.hvac_heating_supp_capacity_w, simulation_output_report.include_enduse_subcategories, simulation_output_report.natural_gas_central_system_heating_therm, simulation_output_report.natural_gas_clothes_dryer_therm, simulation_output_report.natural_gas_cooking_range_therm, simulation_output_report.natural_gas_fireplace_therm, simulation_output_report.natural_gas_grill_therm, simulation_output_report.natural_gas_heating_therm, simulation_output_report.natural_gas_hot_tub_heater_therm, simulation_output_report.natural_gas_lighting_therm, simulation_output_report.natural_gas_pool_heater_therm, simulation_output_report.natural_gas_water_systems_therm, simulation_output_report.propane_central_system_heating_mbtu, simulation_output_report.propane_clothes_dryer_mbtu, simulation_output_report.propane_cooking_range_mbtu, simulation_output_report.propane_heating_mbtu, simulation_output_report.propane_water_systems_mbtu, simulation_output_report.roof_area_ft_2, simulation_output_report.size_cooling_system_kbtu_h, simulation_output_report.size_heating_system_kbtu_h, simulation_output_report.size_water_heater_gal, simulation_output_report.total_site_electricity_kwh, simulation_output_report.total_site_energy_mbtu, simulation_output_report.total_site_fuel_oil_mbtu, simulation_output_report.total_site_natural_gas_therm, simulation_output_report.total_site_propane_mbtu, simulation_output_report.total_site_wood_mbtu, simulation_output_report.wall_area_above_grade_conditioned_ft_2, simulation_output_report.wall_area_above_grade_exterior_ft_2, simulation_output_report.wall_area_below_grade_ft_2, simulation_output_report.window_area_ft_2, simulation_output_report.wood_heating_mbtu, qoi_report.applicable, qoi_report.average_maximum_daily_timing_cooling_hour, qoi_report.average_maximum_daily_timing_heating_hour, qoi_report.average_maximum_daily_timing_overlap_hour, qoi_report.average_maximum_daily_use_cooling_kw, qoi_report.average_maximum_daily_use_heating_kw, qoi_report.average_maximum_daily_use_overlap_kw, qoi_report.average_minimum_daily_use_cooling_kw, qoi_report.average_minimum_daily_use_heating_kw, qoi_report.average_minimum_daily_use_overlap_kw, qoi_report.average_of_top_ten_highest_peaks_timing_cooling_hour, ...]
Index: []

[0 rows x 140 columns]

### Functions

In [5]:
def get_per_unit_sim_output(df, ref):
    """
    ref (df): baseline df
    """
    cols = [x for x in df.columns if 
            x.endswith('_kwh') or
            x.endswith('_mbtu') or
            x.endswith('_therm') or
            x.endswith('_cost_usd') or
            x.endswith('_ft_2')
           ]
    res = ref.set_index('building_id').reindex(df['building_id']).reset_index()
    df.loc[:, cols] = df.loc[:, cols].replace([None,''],np.nan).divide(
        res['build_existing_model.units_represented'], axis=0)
    
    return df
print('func loaded: "get_per_unit_sim_output"')

def get_per_unit_sim_output_limited(df, ref):
    """
    To reduce computing time
    ref (df): baseline df
    """
    cols = ['simulation_output_report.total_site_natural_gas_therm',
            'simulation_output_report.total_site_electricity_kwh',
            'simulation_output_report.total_site_energy_mbtu',
            'simulation_output_report.upgrade_cost_usd'
           ]
    res = ref.set_index('building_id').reindex(df['building_id']).reset_index()
    df.loc[:, cols] = df.loc[:, cols].replace([None,''],np.nan).divide(
        res['build_existing_model.units_represented'], axis=0)
    
    return df
print('func loaded: "get_per_unit_sim_output_limited"')

def add_sqft_eui(df, ref):
    """
    ARG:
        ref (df): baseline df
    RETURN:
        df with added cols: 'sqft', 'gas_eui_thermpersqft','elec_eui_kwhpersqft','site_eui_kbtupersqft'
    """
    res = ref.set_index('building_id').reindex(df['building_id']).reset_index()
    df['sqft'] = res['simulation_output_report.floor_area_conditioned_ft_2']
    df['gas_eui_thermpersqft'] = df['simulation_output_report.total_site_natural_gas_therm'].divide(df['sqft']) # therm/sqft
    df['elec_eui_kwhpersqft'] = df['simulation_output_report.total_site_electricity_kwh'].divide(df['sqft']) # kwh/sqft
    df['site_eui_kbtupersqft'] = df['simulation_output_report.total_site_energy_mbtu'].divide(df['sqft'])*1000 # kbtu/sqft
    
    for col in ['sqft','gas_eui_thermpersqft','elec_eui_kwhpersqft','site_eui_kbtupersqft']:
        df.loc[df['simulation_output_report.applicable']==False, col] = np.nan
    
    return df
print('func loaded: "add_sqft_eui"')

def get_res_by_prototype(df, filter_by_df, row):
    """
    ARG:
        df (dataframe): df to slice on
        filter_by_df (dataframe): df used to do the slicing
    RETURN:
        filtered df (dataframe)
    """
    slice_by_df = filter_by_df.copy().set_index('building_id').reindex(df['building_id']).reset_index()
    res_group_i = df[slice_by_df['build_existing_model.geometry_stories'].isin(row['Stories'].split(',')) & \
        slice_by_df['build_existing_model.geometry_wall_type'].isin(row['WallType'].split(',')) & \
        slice_by_df['build_existing_model.vintage_acs'].isin(row['Vintage'].split(',')) & \
        slice_by_df['build_existing_model.geometry_building_type_recs'].isin(['Single-Family Detached'])]
    res_group_i = res_group_i[res_group_i['completed_status']=="Success"]
    
    return res_group_i
print('func loaded: "get_res_by_prototype"')

def load_upgrade(n, file_dir=result_path):
    """
    ARG:
        n (int, str): upgrade number
        file_dir (str): folder in which upgrade can be found, default to main result dir
    RETURN:
        df (dataframe) of upgrade n
    """
    df = pd.read_parquet(os.path.join(file_dir,'upgrades',
                                     f'upgrade={n}/results_up{n:02d}.parquet'))
    return df
print('func loaded: "load_upgrade"')

func loaded: "get_per_unit_sim_output"
func loaded: "get_per_unit_sim_output_limited"
func loaded: "add_sqft_eui"
func loaded: "get_res_by_prototype"
func loaded: "load_upgrade"

### 1. BASELINE results

In [6]:
save_a_copy_in_csv = False # <-----
res = pd.read_parquet(os.path.join(result_path,'baseline','results_up00.parquet'))

# (1) get sqft, gas/elec/site eui
res = add_sqft_eui(res, res)

if save_a_copy_in_csv:
    res.to_csv(os.path.join(combined_res_csv_path,'results_baseline.csv'), index=False)
    
# (1) get sim output at the unit level (req for MF)
res = get_per_unit_sim_output(res, res)

# (2) get sqft, gas/elec/site eui - redo to get unit-level results
res = add_sqft_eui(res, res)

# check
n_bldgs = 40000
jobs_missing = set(range(1,100)) - set(res.job_id.unique())
print(f'- {len(jobs_missing)} jobs missing: {jobs_missing}')
print(f'- {n_bldgs-len(res)} buildings ({((n_bldgs-len(res))/n_bldgs*100):.2f}%)')

res

- 0 jobs missing: set()
- 0 buildings (0.00%)

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,build_existing_model.ahs_region,build_existing_model.applicable,...,qoi_report.average_of_top_ten_highest_peaks_timing_cooling_hour,qoi_report.average_of_top_ten_highest_peaks_timing_heating_hour,qoi_report.average_of_top_ten_highest_peaks_use_cooling_kw,qoi_report.average_of_top_ten_highest_peaks_use_heating_kw,qoi_report.peak_magnitude_timing_kw,qoi_report.peak_magnitude_use_kw,sqft,gas_eui_thermpersqft,elec_eui_kwhpersqft,site_eui_kbtupersqft
0,1,53,2021-08-07 03:41:05,2021-08-07 03:42:31,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.909091,18.272727,18.471290,14.904212,4697.0,20.325657,885.0,1.148604,11.168373,152.941058
1,2,215,2021-08-07 00:27:52,2021-08-07 00:29:20,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,15.545455,18.090909,32.122713,22.346863,4721.0,34.274634,1138.0,1.362486,9.549978,168.802017
2,3,163,2021-08-07 11:04:20,2021-08-07 11:05:56,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.090909,18.454545,16.643374,9.903358,4721.0,18.064943,3301.0,0.458054,3.038725,56.163079
3,4,64,2021-08-07 00:51:31,2021-08-07 01:06:52,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,15.727273,15.636364,168.463972,163.525441,67.0,264.587701,1138.0,0.452729,4.975331,62.238597
4,5,95,2021-08-07 08:43:53,2021-08-07 08:45:16,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.727273,18.454545,12.295530,9.090699,4743.0,14.355050,1690.0,0.676688,4.275971,82.242834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,39996,196,2021-08-07 08:04:35,2021-08-07 08:06:03,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,15.181818,17.181818,16.726834,8.380572,4936.0,18.167156,1690.0,1.362277,4.771245,152.475348
39996,39997,43,2021-08-07 08:43:16,2021-08-07 08:44:45,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,14.454545,16.636364,30.117522,32.788914,5847.0,40.114838,1220.0,1.193936,6.134555,140.297106
39997,39998,125,2021-08-07 06:17:39,2021-08-07 07:08:00,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,19.454545,18.363636,231.216907,156.646014,5156.0,249.387441,617.0,0.341897,5.243234,52.072206
39998,39999,17,2021-08-07 09:33:56,2021-08-07 09:35:37,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.272727,16.909091,30.702417,12.548276,5057.0,32.450452,8194.0,0.444835,2.092230,51.611927
39999,40000,139,2021-08-07 09:58:38,2021-08-07 10:00:13,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.909091,18.363636,13.519295,10.631421,4722.0,15.456611,2663.0,0.402650,3.862878,53.436034

In [7]:
# assign heating/cooling
cooling_col = 'build_existing_model.hvac_cooling_type'
heating_col = 'build_existing_model.hvac_heating_type_and_fuel'
print('selected')

# if using a national run
if iteration == '_national_2018':
    res = res[res['build_existing_model.ahs_region']=='CBSA Chicago-Naperville-Elgin, IL-IN-WI'].reset_index(drop=True)
    res

selected

### 1.1. Check housing charateristics distributions in BASELINE

In [8]:
proto_chars = ['build_existing_model.geometry_stories',
              'build_existing_model.geometry_wall_type',
              'build_existing_model.vintage_acs',
              cooling_col,
              heating_col,
              'build_existing_model.geometry_floor_area'
             ]

Ns = len(res.query('completed_status=="Success"')); N = len(res)
print(f'>>> ResStock - {iter_path} - BASELINE result summary:\n')
print(f'  * {Ns} / {N} samples ran successfully, {N-Ns} failed, efficacy: {Ns/N:.1%} \n')

print('>>> Housing characteristics splits:\n')

Res_char = []
for i, char in enumerate(proto_chars,1):
    Nchar = res.groupby(char)['building_id'].count()
    Nchar = Nchar/Ns
    Nchar['N_failed'] = len(res[res[char].isnull()])
    print(f'  * [{i}] {Nchar}\n')
    
    ## append for export
    Nchar = Nchar.rename('fraction').to_frame()
    Nchar['housing_char'] = Nchar.index.name
    Res_char.append(Nchar)
    
Res_char = pd.concat(Res_char, axis=0)
Res_char.index.name = 'sub_char'
Res_char = Res_char.reset_index()
Res_char = Res_char[['housing_char','sub_char','fraction']]

Res_char.to_csv(os.path.join(result_path, 'baseline', 'baseline_housing_char_breakdown.csv'), index=False)
print(f'>>> file saved to:\n  {os.path.join(result_path, "baseline")}')

>>> ResStock - cookcnty_packages_paper_all - BASELINE result summary:

  * 39976 / 40000 samples ran successfully, 24 failed, efficacy: 99.9%

>>> Housing characteristics splits:

  * [1] build_existing_model.geometry_stories
1            0.525790
2            0.260106
3            0.214103
N_failed    24.000000
Name: building_id, dtype: float64

  * [2] build_existing_model.geometry_wall_type
Masonry      0.715204
WoodStud     0.284796
N_failed    24.000000
Name: building_id, dtype: float64

  * [3] build_existing_model.vintage_acs
1940-59      0.235066
1960-79      0.255003
1980-99      0.137833
2000-09      0.076146
2010s        0.011682
<1940        0.284271
N_failed    24.000000
Name: building_id, dtype: float64

  * [4] build_existing_model.hvac_cooling_type
Central AC     0.616595
Heat Pump      0.025615
None           0.052206
Room AC        0.305583
N_failed      24.000000
Name: building_id, dtype: float64

  * [5] build_existing_model.hvac_heating_type_and_fuel
Electricity ASHP                        0.020262
Electricity Baseboard                   0.044477
Electricity Electric Boiler             0.000750
Electricity Electric Furnace            0.029092
Electricity Electric Wall Furnace       0.000926
Electricity Shared Heating              0.035321
Fuel Oil Fuel Boiler                    0.000125
Fuel Oil Fuel Furnace                   0.000550
Natural Gas Fuel Boiler                 0.093781
Natural Gas Fuel Furnace                0.513308
Natural Gas Fuel Wall/Floor Furnace     0.100360
None None                               0.007680
Propane Fuel Boiler                     0.000425
Propane Fuel Furnace                    0.006329
Propane Fuel Wall/Floor Furnace         0.001726
Void                                    0.144887
N_failed                               24.000000
Name: building_id, dtype: float64

  * [6] build_existing_model.geometry_floor_area
0-499         0.048554
1000-1499     0.292926
1500-1999     0.169627
2000-2499     0.091055
2500-2999     0.039849
3000-3999     0.048904
4000+         0.020863
500-749       0.096883
750-999       0.191340
N_failed     24.000000
Name: building_id, dtype: float64

>>> file saved to:
  /Users/lliu2/Documents/Chicago retrofits/ResStock results/cookcnty_packages_paper_all/baseline

### 1.2. Add additional metrics to Baseline

In [7]:
## EE prototype tags
res['vintage_ee'] = '3: post-1978'
res.loc[res['build_existing_model.vintage_acs'].isin(['1940-59','1960-79']),'vintage_ee'] = '2: 1942-1978'
res.loc[res['build_existing_model.vintage_acs']=='<1940','vintage_ee'] = '1: pre-1942'

res['stories'] = '2: 2+ stories'
res.loc[res['build_existing_model.geometry_stories']=='1','stories'] = '1: <2 stories'

print('new cols added to "res"')
res

new cols added to "res"

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,build_existing_model.ahs_region,build_existing_model.applicable,...,qoi_report.average_of_top_ten_highest_peaks_use_cooling_kw,qoi_report.average_of_top_ten_highest_peaks_use_heating_kw,qoi_report.peak_magnitude_timing_kw,qoi_report.peak_magnitude_use_kw,sqft,gas_eui_thermpersqft,elec_eui_kwhpersqft,site_eui_kbtupersqft,vintage_ee,stories
0,1,53,2021-08-07 03:41:05,2021-08-07 03:42:31,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,18.471290,14.904212,4697.0,20.325657,885.0,1.148604,11.168373,152.941058,2: 1942-1978,1: <2 stories
1,2,215,2021-08-07 00:27:52,2021-08-07 00:29:20,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,32.122713,22.346863,4721.0,34.274634,1138.0,1.362486,9.549978,168.802017,2: 1942-1978,1: <2 stories
2,3,163,2021-08-07 11:04:20,2021-08-07 11:05:56,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.643374,9.903358,4721.0,18.064943,3301.0,0.458054,3.038725,56.163079,3: post-1978,2: 2+ stories
3,4,64,2021-08-07 00:51:31,2021-08-07 01:06:52,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,168.463972,163.525441,67.0,264.587701,1138.0,0.452729,4.975331,62.238597,2: 1942-1978,2: 2+ stories
4,5,95,2021-08-07 08:43:53,2021-08-07 08:45:16,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,12.295530,9.090699,4743.0,14.355050,1690.0,0.676688,4.275971,82.242834,3: post-1978,2: 2+ stories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,39996,196,2021-08-07 08:04:35,2021-08-07 08:06:03,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.726834,8.380572,4936.0,18.167156,1690.0,1.362277,4.771245,152.475348,1: pre-1942,2: 2+ stories
39996,39997,43,2021-08-07 08:43:16,2021-08-07 08:44:45,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,30.117522,32.788914,5847.0,40.114838,1220.0,1.193936,6.134555,140.297106,2: 1942-1978,1: <2 stories
39997,39998,125,2021-08-07 06:17:39,2021-08-07 07:08:00,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,231.216907,156.646014,5156.0,249.387441,617.0,0.341897,5.243234,52.072206,3: post-1978,2: 2+ stories
39998,39999,17,2021-08-07 09:33:56,2021-08-07 09:35:37,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,30.702417,12.548276,5057.0,32.450452,8194.0,0.444835,2.092230,51.611927,1: pre-1942,2: 2+ stories
39999,40000,139,2021-08-07 09:58:38,2021-08-07 10:00:13,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,13.519295,10.631421,4722.0,15.456611,2663.0,0.402650,3.862878,53.436034,2: 1942-1978,1: <2 stories

### 1.3. Get BASELINE results by building prototypes from Elevate Energy
#### Note: cannot add prototype tags directly to ResStock results as prototypes overlap in chars

In [9]:
## Load prototype csv
groups = pd.read_csv(os.path.join(result_dir,'Groups.csv'))
print('prototypes loaded')

prototypes loaded

In [10]:
### (1) get count & median consumption
Metric_map1 = {'count': 'completed_status',
           'median gas': 'simulation_output_report.total_site_natural_gas_therm',
           'median elec': 'simulation_output_report.total_site_electricity_kwh'}

for i, row in groups.iterrows():
    res_group_i = get_res_by_prototype(res, res, row) # <----
    
    for metric, res_var in Metric_map1.items():
        if metric == 'count':
            groups.loc[i, 'count'] = len(res_group_i)
        else:
            groups.loc[i, metric] = res_group_i[res_var].median()

groups['Gas Diff-med(%)'] = ((groups['Non-normalized gas usage'] - groups['median gas']) / groups['Non-normalized gas usage']) * 100
groups['Elec Diff-med(%)'] = ((groups['Non-normalized elec. usage'] - groups['median elec']) / groups['Non-normalized elec. usage']) * 100
print('>> (1) median consumption computed')

>> (1) median consumption computed

In [11]:
res2 = []

for i, row in groups.iterrows():
    if row['HousingGroupName'] not in \
        ['Masonry All Years Split Level','Frame Post-1978 Split Level','Frame Pre-1942 Split Level']:
        res_group_i = get_res_by_prototype(res, res, row) # <----
        res_group_i['prototype'] = row['HousingGroupName']
        res2.append(res_group_i)

res2 = pd.concat(res2, axis=0).sort_values(by=['building_id'])
display(res2)

res2 = res2.set_index('building_id').reindex(res['building_id']).reset_index()
res.loc[res2['prototype'].isnull(),:]

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,build_existing_model.ahs_region,build_existing_model.applicable,...,qoi_report.average_of_top_ten_highest_peaks_timing_heating_hour,qoi_report.average_of_top_ten_highest_peaks_use_cooling_kw,qoi_report.average_of_top_ten_highest_peaks_use_heating_kw,qoi_report.peak_magnitude_timing_kw,qoi_report.peak_magnitude_use_kw,sqft,gas_eui_thermpersqft,elec_eui_kwhpersqft,site_eui_kbtupersqft,prototype
0,1,53,2021-08-07 03:41:05,2021-08-07 03:42:31,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,18.272727,18.471290,14.904212,4697.0,20.325657,885.0,1.148604,11.168373,152.941058,Masonry 1942-1978 Less than 2 Stories
2,3,163,2021-08-07 11:04:20,2021-08-07 11:05:56,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,18.454545,16.643374,9.903358,4721.0,18.064943,3301.0,0.458054,3.038725,56.163079,Masonry Post-1978 2 or more stories
4,5,95,2021-08-07 08:43:53,2021-08-07 08:45:16,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,18.454545,12.295530,9.090699,4743.0,14.355050,1690.0,0.676688,4.275971,82.242834,Frame Post-1978 2 or more stories
5,6,21,2021-08-07 06:33:44,2021-08-07 06:35:07,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,18.454545,11.855922,9.852629,4002.0,12.591113,2176.0,0.578731,4.654541,73.741262,Frame 1942-1978 less than 2 stories
6,7,112,2021-08-07 10:15:26,2021-08-07 10:16:46,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,12.454545,15.530622,27.958082,138.0,30.585420,1690.0,0.000000,11.632000,39.689999,Frame Post-1978 Less than 2 stories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39989,39990,2,2021-08-06 22:11:27,2021-08-06 22:12:56,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,13.454545,34.723179,24.971366,4430.0,39.386725,2176.0,0.769909,4.136341,91.086311,Frame Pre-1942 2 or more stories
39993,39994,70,2021-08-07 06:30:29,2021-08-07 06:31:53,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,17.909091,17.024001,12.566405,4795.0,19.721980,1220.0,1.702032,8.437547,198.952769,Masonry Pre-1942 2 or more stories
39995,39996,196,2021-08-07 08:04:35,2021-08-07 08:06:03,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,17.181818,16.726834,8.380572,4936.0,18.167156,1690.0,1.362277,4.771245,152.475348,Masonry Pre-1942 2 or more stories
39998,39999,17,2021-08-07 09:33:56,2021-08-07 09:35:37,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.909091,30.702417,12.548276,5057.0,32.450452,8194.0,0.444835,2.092230,51.611927,Masonry Pre-1942 2 or more stories
39999,40000,139,2021-08-07 09:58:38,2021-08-07 10:00:13,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,18.363636,13.519295,10.631421,4722.0,15.456611,2663.0,0.402650,3.862878,53.436034,Masonry 1942-1978 Less than 2 Stories

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,build_existing_model.ahs_region,build_existing_model.applicable,...,qoi_report.average_of_top_ten_highest_peaks_timing_cooling_hour,qoi_report.average_of_top_ten_highest_peaks_timing_heating_hour,qoi_report.average_of_top_ten_highest_peaks_use_cooling_kw,qoi_report.average_of_top_ten_highest_peaks_use_heating_kw,qoi_report.peak_magnitude_timing_kw,qoi_report.peak_magnitude_use_kw,sqft,gas_eui_thermpersqft,elec_eui_kwhpersqft,site_eui_kbtupersqft
1,2,215,2021-08-07 00:27:52,2021-08-07 00:29:20,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,15.545455,18.090909,32.122713,22.346863,4721.0,34.274634,1138.0,1.362486,9.549978,168.802017
3,4,64,2021-08-07 00:51:31,2021-08-07 01:06:52,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,15.727273,15.636364,168.463972,163.525441,67.0,264.587701,1138.0,0.452729,4.975331,62.238597
9,10,103,2021-08-07 04:22:04,2021-08-07 04:25:31,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.090909,16.181818,99.423338,80.785096,5156.0,110.199843,2115.0,0.588587,5.599949,77.952497
11,12,164,2021-08-07 06:02:05,2021-08-07 06:03:38,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,14.818182,18.818182,23.689308,16.190775,4626.0,26.813113,853.0,0.772833,7.784623,103.827100
12,13,207,2021-08-06 23:36:45,2021-08-06 23:57:02,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,12.000000,13.454545,275.082848,659.409178,621.0,859.329596,853.0,0.000000,17.103477,58.359439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39991,39992,8,2021-08-06 22:51:56,2021-08-06 23:37:50,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.181818,12.181818,706.148556,1010.480047,656.0,1138.966139,617.0,0.031215,20.504692,73.085634
39992,39993,71,2021-08-07 03:59:17,2021-08-07 04:14:36,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,9.181818,13.636364,1248.149408,1180.663499,7124.0,1364.992653,1138.0,0.431623,5.243995,61.045262
39994,39995,212,2021-08-07 03:17:27,2021-08-07 03:28:13,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,16.454545,6.000000,150.464721,778.832166,630.0,903.495965,853.0,0.000000,19.505030,66.553871
39996,39997,43,2021-08-07 08:43:16,2021-08-07 08:44:45,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,14.454545,16.636364,30.117522,32.788914,5847.0,40.114838,1220.0,1.193936,6.134555,140.297106
39997,39998,125,2021-08-07 06:17:39,2021-08-07 07:08:00,Success,None,None,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,19.454545,18.363636,231.216907,156.646014,5156.0,249.387441,617.0,0.341897,5.243234,52.072206

In [12]:
### (2) get mean consumption
Metric_map2 = {'mean gas': 'simulation_output_report.total_site_natural_gas_therm',
           'mean elec': 'simulation_output_report.total_site_electricity_kwh'} # metric: res_var

for i, row in groups.iterrows():
    res_group_i = get_res_by_prototype(res, res, row) # <----
    
    for metric, res_var in Metric_map2.items():
        groups.loc[i, metric] = res_group_i[res_var].mean()

groups['Gas Diff-mean(%)'] = ((groups['Non-normalized gas usage'] - groups['mean gas']) / groups['Non-normalized gas usage']) * 100
groups['Elec Diff-mean(%)'] = ((groups['Non-normalized elec. usage'] - groups['mean elec']) / groups['Non-normalized elec. usage']) * 100
print('>> (2) mean consumption computed')

>> (2) mean consumption computed

In [13]:
### (3) get median & mean sqft & eui
Metric_map1 = {'median sqft': 'sqft',
               'median gas eui': 'gas_eui_thermpersqft', 
               'median elec eui': 'elec_eui_kwhpersqft'}
Metric_map2 = {'mean sqft': 'sqft', 
               'mean gas eui': 'gas_eui_thermpersqft', 
               'mean elec eui': 'elec_eui_kwhpersqft'}

for i, row in groups.iterrows():
    res_group_i = get_res_by_prototype(res, res, row) # <----
    
    ### (3.1) get median values
    for metric, res_var in Metric_map1.items():
        groups.loc[i, metric] = res_group_i[res_var].median()

    ### (3.2) get mean values
    for metric, res_var in Metric_map2.items():
        groups.loc[i, metric] = \
            res_group_i[res_var].mean()

print('>> (3) median & mean sqft & eui computed:');

groups.set_index(['HousingGroupNo','HousingGroupName'])[['median sqft', 'mean sqft',
                                                         'median gas','mean gas',
                                                         'median gas eui', 'mean gas eui', 
                                                         'median elec','mean elec', 
                                                         'median elec eui','mean elec eui']]

>> (3) median & mean sqft & eui computed:

,,median sqft,mean sqft,median gas,mean gas,median gas eui,mean gas eui,median elec,mean elec,median elec eui,mean elec eui
HousingGroupNo,HousingGroupName,,,,,,,,,,
1,Masonry Post-1978 less than 2 stories,2176.0,2394.582482,809.308687,894.332363,0.406559,0.437425,8440.936673,9490.714781,4.045196,4.674872
2,Masonry All Years Split Level,1690.0,2000.196867,1159.439160,1284.792342,0.692642,0.735943,8613.432377,9980.696462,5.060779,5.833198
3,Masonry Post-1978 2 or more stories,3301.0,4058.270428,1325.510707,1360.603063,0.386586,0.417654,11120.401577,13035.583596,3.388056,3.860663
4,Masonry 1942-1978 Less than 2 Stories,1690.0,1680.132653,1041.429299,1136.220521,0.690103,0.723654,8144.416802,9195.582789,5.273003,6.023709
5,Masonry 1942-1978 2 or more stories,2176.0,2392.638539,1582.221520,1668.734098,0.759054,0.785283,9717.522000,11408.306454,4.647827,5.536763
6,Masonry Pre-1942 less than 2 stories,1220.0,1460.060606,1360.303882,1432.475178,1.016660,1.061279,8265.615413,9336.790323,6.323633,6.988460
7,Masonry Pre-1942 2 or more stories,2176.0,2552.909881,1820.446442,1970.778270,0.872339,0.909833,10238.685940,12595.335795,4.876912,6.005243
8,Frame Post-1978 Less than 2 stories,2176.0,2243.300336,861.384465,937.398865,0.456045,0.480853,8321.603637,9477.627403,4.369752,4.946237
9,Frame Post-1978 Split Level,2176.0,3012.053452,1093.373446,1218.859617,0.465849,0.484178,9351.602446,11310.346666,3.851808,4.538992
10,Frame Post-1978 2 or more stories,2663.0,3622.142477,1341.124887,1442.229268,0.473200,0.486816,10552.009424,12764.808292,3.545848,4.215798
11,Frame 1942-1978 less than 2 stories,1690.0,1690.260624,1105.919023,1196.215070,0.728610,0.762578,8037.312442,9059.302929,5.164393,5.968534
12,Frame Pre-1942 Split Level,1690.0,2020.515977,1795.592652,1907.159530,1.036990,1.086611,9257.078302,10819.392733,5.352132,6.334681
13,Frame 1942-1978 2 or more stories,1690.0,2276.806678,1690.133366,1809.457551,0.872755,0.898865,9477.806151,10854.444209,4.806490,5.442217
14,Frame Pre-1942 less than 2 stories,1220.0,1402.300142,1422.502313,1528.309324,1.152858,1.168796,8011.407903,9448.180731,6.290619,7.376441
15,Frame Pre-1942 2 or more stories,2176.0,2325.502456,1967.820510,2094.058965,0.992683,1.046066,9841.652878,11495.857321,4.873081,5.820746

In [14]:
### export BASELINE prototype summary
groups.to_csv(os.path.join(result_path, 'baseline', 'baseline_prototype_results.csv'), index=True)
print(f'BASELINE prototype summary saved to:\n  {os.path.join(result_path, "baseline")}')

BASELINE prototype summary saved to:
  /Users/lliu2/Documents/Chicago retrofits/ResStock results/cookcnty_packages_paper_all/baseline

## 2B. PACKAGE summary ###

In [15]:
### upgrade result processing funcs
def assign_utility_rates_to_upgrade(upkg_no, p, ref, HVAC_upgrades_rate_change, for_packages=False):
    
    res = ref.set_index('building_id')[['gas_rate', 'gas_fixed', 'gas_CO2_rate',
                                        'elec_rate', 'elec_fixed', 'elec_CO2_rate'
                                       ]]
    ## assign rates
    p['gas_rate'] = p['building_id'].map(res['gas_rate'])
    p['gas_fixed'] = p['building_id'].map(res['gas_fixed'])
    p['gas_CO2_rate'] = p['building_id'].map(res['gas_CO2_rate'])
    p['elec_rate'] = p['building_id'].map(res['elec_rate'])
    p['elec_fixed'] = p['building_id'].map(res['elec_fixed'])
    p['elec_CO2_rate'] = p['building_id'].map(res['elec_CO2_rate'])
    
    if not for_packages:
        # ind upgrades
        for n in HVAC_upgrades_rate_change.keys():
            new_rates = HVAC_upgrades_rate_change[n]
            p.loc[p['simulation_output_report.applicable']==True, 'gas_rate'] = new_rates[0]
            p.loc[p['simulation_output_report.applicable']==True, 'gas_fixed'] = new_rates[1]
            p.loc[p['simulation_output_report.applicable']==True, 'elec_rate'] = new_rates[2]
            p.loc[p['simulation_output_report.applicable']==True, 'elec_fixed'] = new_rates[3]
    else:
        if isinstance(HVAC_upgrades_rate_change, dict):
            # packages with a dict input
            if upkg_no in HVAC_upgrades_rate_change.keys():
                for m in HVAC_upgrades_rate_change[upkg_no]:
                    idx = (p[(p['apply_upgrade.applicable']==True) &
                           (~p[f'simulation_output_report.option_{m:02d}_cost_usd'].isnull())
                            ]).index
                    p.loc[idx, 'gas_rate'] = NGH_rate
                    p.loc[idx, 'gas_fixed'] = NGH_fixed
                    p.loc[idx, 'elec_rate'] = EH_rate
                    p.loc[idx, 'elec_fixed'] = EH_fixed
        
        else:
            # packages with a list input
            for m in HVAC_upgrades_rate_change:
                idx = (p[(p['apply_upgrade.applicable']==True) &
                       (~p[f'simulation_output_report.option_{m:02d}_cost_usd'].isnull())
                        ]).index
                p.loc[idx, 'gas_rate'] = NGH_rate
                p.loc[idx, 'gas_fixed'] = NGH_fixed
                p.loc[idx, 'elec_rate'] = EH_rate
                p.loc[idx, 'elec_fixed'] = EH_fixed
                
    # assign 0 rates to building with no energy use  
    p.loc[p['simulation_output_report.total_site_natural_gas_therm'].isin([0, np.nan]), 'gas_fixed'] = 0 
    p.loc[p['simulation_output_report.total_site_natural_gas_therm'].isin([0, np.nan]), 'gas_rate'] = 0 
    p.loc[p['simulation_output_report.total_site_electricity_kwh'].isin([0, np.nan]), 'elec_fixed'] = 0 
    p.loc[p['simulation_output_report.total_site_electricity_kwh'].isin([0, np.nan]), 'elec_rate'] = 0 
    
    for col in ['gas_rate','gas_fixed','gas_CO2_rate','elec_rate','elec_fixed','elec_CO2_rate']:
        p.loc[p['simulation_output_report.applicable']==False, col] = np.nan

    return p

def combine_upgrade_cost_and_lifetime(p):
    
    ## upgrade costs (sum)
    p['upgrade_cost'] = p['simulation_output_report.upgrade_cost_usd']
    cost_cols = list(x for x in p.columns if x.endswith('cost_usd'))
    p = p.drop(cost_cols, axis=1)
    
    ## upgrade lifetime (min)
    lt_cols = list(x for x in p.columns if x.endswith('lifetime_yrs'))
    p['upgrade_lifetime'] = p[lt_cols].min(axis=1)
    p = p.drop(lt_cols, axis=1)

    p['upgrade_cost'] = p['upgrade_cost'].replace([0, None,''],np.nan)
    p['upgrade_lifetime'] = p['upgrade_lifetime'].replace([0, None,''],np.nan)
    
    return p

def get_annual_totals(pp, get_col_only=False):
    if get_col_only:
        p = pp.copy()
    else:
        p = pp
        
    p['ann_gas_cost'] = \
        p['simulation_output_report.total_site_natural_gas_therm']*p['gas_rate']+p['gas_fixed']
    p['ann_elec_cost'] = \
        p['simulation_output_report.total_site_electricity_kwh']*p['elec_rate']+p['elec_fixed']
    p['ann_energy_cost'] = \
        p['ann_gas_cost'] + p['ann_elec_cost']
    
    p['ann_metric_ton_co2e_gas'] = \
        p['simulation_output_report.total_site_natural_gas_therm']*p['gas_CO2_rate']
    p['ann_metric_ton_co2e_elec'] = \
        p['simulation_output_report.total_site_electricity_kwh']*p['elec_CO2_rate']
    p['ann_metric_ton_co2e'] = \
        p['ann_metric_ton_co2e_gas'] + p['ann_metric_ton_co2e_elec']
    
    if get_col_only:
        return p[['ann_gas_cost','ann_elec_cost','ann_energy_cost',
                 'ann_metric_ton_co2e_gas','ann_metric_ton_co2e_elec','ann_metric_ton_co2e']]
    else:
        return p

def get_annual_gas_elec_site_energy_saving(pp, res, get_col_only=False):
    """
    p: upgrade df
    ref: reference scenario df
    get_col_only: whether to return the computed col only or the entire upgrade df p
    """
    if get_col_only:
        p = pp.copy()
    else:
        p = pp
    ref = res.set_index('building_id').reindex(p['building_id']).reset_index()
    
    p['ann_therm_gas_saving'] = ref['simulation_output_report.total_site_natural_gas_therm']-\
         p['simulation_output_report.total_site_natural_gas_therm']
    p['ann_kwh_elec_saving'] = ref['simulation_output_report.total_site_electricity_kwh']-\
         p['simulation_output_report.total_site_electricity_kwh']
    p['ann_mbtu_site_energy_saving'] = ref['simulation_output_report.total_site_energy_mbtu']-\
        p['simulation_output_report.total_site_energy_mbtu']
    
    if get_col_only:
        return p[['ann_therm_gas_saving','ann_kwh_elec_saving','ann_mbtu_site_energy_saving']]
    else:
        return p

def get_annual_energy_cost_saving(pp, res, get_col_only=False):
    """
    p: upgrade df
    ref: reference scenario df
    get_col_only: whether to return the computed col only or the entire upgrade df p
    """ 
    if get_col_only:
        p = pp.copy()
    else:
        p = pp
    ref = res.set_index('building_id').reindex(p['building_id']).reset_index()
    
    p['ann_gas_cost_saving'] = \
        ref['simulation_output_report.total_site_natural_gas_therm']*ref['gas_rate']+ref['gas_fixed'] - \
        (p['simulation_output_report.total_site_natural_gas_therm']*p['gas_rate']+p['gas_fixed'])
        
    p['ann_elec_cost_saving'] = \
        ref['simulation_output_report.total_site_electricity_kwh']*ref['elec_rate']+ref['elec_fixed'] - \
        (p['simulation_output_report.total_site_electricity_kwh']*p['elec_rate']+p['elec_fixed'])
    
    p['ann_energy_cost_saving'] = p['ann_gas_cost_saving']+p['ann_elec_cost_saving'] #p[['ann_gas_cost_saving','ann_elec_cost_saving']].sum(axis=1)
    
    if get_col_only:
        return p['ann_energy_cost_saving']
    else:
        return p

def get_annual_metric_ton_co2e_saving(pp, res, get_col_only=False):
    """
    p: upgrade df
    ref: reference scenario df
    get_col_only: whether to return the computed col only or the entire upgrade df p
    """
    if get_col_only:
        p = pp.copy()
    else:
        p = pp
    ref = res.set_index('building_id').reindex(p['building_id']).reset_index()
    
    p['ann_metric_ton_co2e_saving_gas'] = \
        (ref['simulation_output_report.total_site_natural_gas_therm']-\
         p['simulation_output_report.total_site_natural_gas_therm'])*p['gas_CO2_rate']
    
    p['ann_metric_ton_co2e_saving_elec'] = \
        (ref['simulation_output_report.total_site_electricity_kwh']-\
         p['simulation_output_report.total_site_electricity_kwh'])*p['elec_CO2_rate']
    
    p['ann_metric_ton_co2e_saving'] = p['ann_metric_ton_co2e_saving_gas'] + p['ann_metric_ton_co2e_saving_elec']
    
    if get_col_only:
        return p['ann_metric_ton_co2e_saving']
    else:
        return p

def print_metrics_report(p, has_comparative_payback=True):
    ### (1) check for simple_payback > 100 yr or if < 0 yr
    if len(p[~p['simple_payback'].isnull()]):
        print(p['simple_payback'].agg(['min','median','max']))
    spb_100 = p[p['simple_payback']>100]
    if len(spb_100)>0:
        print(f'    *PAYBACK1 - too large* upgrade={n} has {len(spb_100)} simple_payback>100 ' +\
              f'(including {len(p[p["simple_payback"]==np.inf])} INF)')
    spb_neg = p[p['simple_payback']<0]
    if len(spb_neg)>0:
        print(f'    *PAYBACK1 - negative*  upgrade={n} has {len(spb_neg)} simple_payback<0 ' +\
              '(due to negative energy cost saving)')

    ### (2) check for comparative_payback > 100 yr or if < 0 yr
    if has_comparative_payback:
        if len(p[~p['comparative_payback'].isnull()]):
            print(p['comparative_payback'].agg(['min','median','max']))
        spb_100 = p[p['comparative_payback']>100]
        if len(spb_100)>0:
            print(f'    *PAYBACK2 - too large* upgrade={n} has {len(spb_100)} comparative_payback>100 ' +\
                  f'(including {len(p[p["comparative_payback"]==np.inf])} INF)')
        spb_neg = p[p['comparative_payback']<0]
        if len(spb_neg)>0:
            print(f'    *PAYBACK2 - negative*  upgrade={n} has {len(spb_neg)} comparative_payback<0 ' +\
                  '(due to negative energy cost saving)')

    ### (3) check for eui==inf
    for eui in ['pct_delta_gas_eui','pct_delta_elec_eui','pct_delta_site_eui']:
        eui_inf = p[p[eui]==np.inf]
        if len(eui_inf)>0:
            print(f'       *EUI - inf* upgrade={n} has {len(eui_inf)} {eui}=INF ' +\
                  '(due to fuel introduction from upgrade)')

    ### (4) check for neg carbon savings
    ces_neg = p[p['ann_metric_ton_co2e_saving']<0]
    if len(ces_neg)>0:
        print(f'    *CARBON - negative*  upgrade={n} has {len(ces_neg)} carbon saving<0 ')
        
print('funcs loaded')

funcs loaded

In [18]:
### set utility rates ###
NG_rate_multiplier = 1 # <-----

if NG_rate_multiplier > 1:
    fn_ext = f'_{NG_rate_multiplier}x_gas_prices' # file name extension to add to relevant results
else:
    fn_ext = ''

### utility rates ###########################################
# ref (EIA): 
# avg ComEd res elec rate 2019: $ 0.1330 /kWh
# weighted avg IL gas rate 2019: $ 0.77183 /therm

## electricity ##
# annual fixed rates = monthly x 12
EH_fixed = 15.70 * 12 # annual
NEH_fixed = 14.28 * 12 # annual
# avg of summer rates (J,J,A,S) and non-summer rates
EH_rate = (0.10273*4+0.10952*8)/12 # 0.10726, $/kWh, electric rate for electric heating customers
NEH_rate = (0.12168*4+0.12847*8)/12 # 0.12621, $/kWh, electric rate for non-electric heating customers
# marginal carbon emission factor:
elec_CO2_rate = 0.000834702 # metric tons of CO2e/kWh (0.2446 tons/mbtu)

## gas ##
# annual fixed rates = monthly x 12
GH_fixed = 45.32 * 12
NGH_fixed = 21.51 * 12
# variable rates
GH_rate = 0.61648 * NG_rate_multiplier # 0.19477, $/therm, gas rate for NG heating customers
NGH_rate = 0.56758 * NG_rate_multiplier # 0.14964, $/therm, gas rate for non-NG heating customers
# marginal carbon emission factor:
gas_CO2_rate = 0.00532181 # metric tons of CO2e/therm (0.0532 tons/mbtu)

### upgrades that will cause utility rate change: ###########################################
HVAC_upgrades_rate_change = {
    6: [24,25,26,27], # elec basic
    7: [24,25,26,27,28,29,30], # elec HP,
    8: [26,27,28,29,30,31,32], # elec HP + eff,
    10: [47,48,49,50,51,52,53], # full upgrade ele
}

# assign rates accordingly
Elec_heating_types = ['Electricity Baseboard','Electricity ASHP','Electricity Electric Furnace',
                      'Electricity Electric Boiler', 'Electricity Electric Wall Furnace']
NG_heating_types = ['Natural Gas Fuel Wall/Floor Furnace', 'Natural Gas Fuel Furnace',
                    'Natural Gas Fuel Boiler']

res['gas_rate'] = NGH_rate
res['gas_fixed'] = NGH_fixed
res['gas_CO2_rate'] = gas_CO2_rate
res['elec_rate'] = NEH_rate
res['elec_fixed'] = NEH_fixed
res['elec_CO2_rate'] = elec_CO2_rate

res.loc[(res[res['build_existing_model.hvac_heating_type_and_fuel'].isin(NG_heating_types)]).index,
       'gas_rate'] = GH_rate
res.loc[(res[res['build_existing_model.hvac_heating_type_and_fuel'].isin(NG_heating_types)]).index,
       'gas_fixed'] = GH_fixed
res.loc[(res[res['build_existing_model.hvac_heating_type_and_fuel'].isin(Elec_heating_types)]).index,
        'elec_rate'] = EH_rate
res.loc[(res[res['build_existing_model.hvac_heating_type_and_fuel'].isin(Elec_heating_types)]).index,
        'elec_fixed'] = EH_fixed

# assign 0 gas rates to building with no gas use 
res.loc[res['simulation_output_report.total_site_natural_gas_therm'].isin([0, np.nan]), 'gas_fixed'] = 0 
res.loc[res['simulation_output_report.total_site_natural_gas_therm'].isin([0, np.nan]), 'gas_rate'] = 0 
res.loc[res['simulation_output_report.total_site_electricity_kwh'].isin([0, np.nan]), 'elec_fixed'] = 0 
res.loc[res['simulation_output_report.total_site_electricity_kwh'].isin([0, np.nan]), 'elec_rate'] = 0

for col in ['gas_rate','gas_fixed','gas_CO2_rate','elec_rate','elec_fixed','elec_CO2_rate']:
    res.loc[res['completed_status']!='Success', col] = np.nan

print(f'Natural gas rate multiplier: {NG_rate_multiplier}')

Natural gas rate multiplier: 1

In [1]:
(0.10273*4+0.10952*8)/12

0.10725666666666667

In [2]:
(0.12168*4+0.12847*8)/12

0.12620666666666666

### Get baseline results

In [19]:
#### count upgrades
N_upgrades = 10 # <---

print(f'>>> {iter_path} has {N_upgrades:,} packages')
print(f'Natural gas rate multiplier: {NG_rate_multiplier}')
    
## get summary table
summary_upgrades = []
package_list = list(range(1,11))
for n in package_list:
    p = pd.read_parquet(os.path.join(result_path, 'upgrades', f'upgrade={n}',
                                     f'results_up{n:02d}.parquet'))
    print(f'\nPackage {n}')
    
    ### get sim output at unit level
    p = get_per_unit_sim_output_limited(p, res)

    ### assign utility rates
    p = assign_utility_rates_to_upgrade(n, p, res, HVAC_upgrades_rate_change, for_packages=True)
    
    ### collapse upgrade cost and lifetime cols
    p = combine_upgrade_cost_and_lifetime(p)

    ### check if upgrade has 0 successful sims
    if len(p[p['completed_status']=='Success']) == 0:
        print(f' * upgrade={n} has 0 successful simulations')

    ### calculate metrics
    p = add_sqft_eui(p, res)
    EUIi = ['gas_eui_thermpersqft','elec_eui_kwhpersqft','site_eui_kbtupersqft']
    EUIo = ['gas_eui','elec_eui','site_eui']
    for vari, varo in zip(EUIi, EUIo):
        p[f'pct_delta_{varo}'] = ((p[vari]-res[vari])/res[vari]*100)


    # annual energy saving:
    p = get_annual_gas_elec_site_energy_saving(p, res)

    # annual energy cost saving:
    p = get_annual_energy_cost_saving(p, res)
    
    # annual kBtu saved per upgrade cost:
    p['ann_kbtu_saved_per_dollar'] = p['ann_mbtu_site_energy_saving'].divide(
                            p['upgrade_cost'], axis=0)*1000

    # simple payback
    p['simple_payback'] = p['upgrade_cost']/p['ann_energy_cost_saving']

    # annual metric ton carbon emission savings:
    p = get_annual_metric_ton_co2e_saving(p, res)

    ### check for neg/large paybacks, inf eui, neg carbon savings 
    print_metrics_report(p, has_comparative_payback=False)
    
    ### subset to only those that have been applied with the upgrades successfully:
    upgrade_name = p['apply_upgrade.upgrade_name'].replace('',np.nan).dropna(axis=0).unique()[0]
    p = p[p['apply_upgrade.applicable']==True].reset_index(drop=True)
    p['package_no'] = n
    
    ### export upgrade results to csv 
    p.to_csv(os.path.join(combined_res_csv_path, f'results_package{n:02d}{fn_ext}.csv'), index=False)
    
    for eui in ['pct_delta_gas_eui','pct_delta_elec_eui','pct_delta_site_eui']:
        p[eui] = p[eui].replace([np.inf, -np.inf], np.nan) # for mean calc
        
    ### add to summary table
    summ = pd.DataFrame()
    summ.loc[0,'upgrade_no'] = n
    summ.loc[0,'upgrade_name'] = upgrade_name
    summ.loc[0,'n_applied'] = len(p)
    summ.loc[0,'n_success'] = len(p[p['completed_status']=='Success'])
    summ.loc[0,'n_fail'] = len(p[p['completed_status']=='Fail'])
    summ['pct_success'] = round(summ['n_success']/summ['n_applied']*100,3)

    p = p[p['completed_status']=='Success'].reset_index(drop=True)
    summ['mean_ann_therm_gas_saving'] = round(p['ann_therm_gas_saving'].mean(), 3)
    summ['mean_ann_kwh_elec_saving'] = round(p['ann_kwh_elec_saving'].mean(), 3)
    summ['mean_ann_mbtu_site_energy_saving'] = round(p['ann_mbtu_site_energy_saving'].mean(), 3)
    summ['mean_pct_delta_gas_eui'] = round(p['pct_delta_gas_eui'].mean(), 3)
    summ['mean_pct_delta_elec_eui'] = round(p['pct_delta_elec_eui'].mean(), 3)
    summ['mean_pct_delta_site_eui'] = round(p['pct_delta_site_eui'].mean(), 3)
    summ['mean_upgrade_cost'] = round(p['upgrade_cost'].mean(),2)
    summ['mean_ann_kbtu_saved_per_dollar'] = round(p['ann_kbtu_saved_per_dollar'].mean(),3) # annual kBtu saved per upgrade cost
    summ['mean_ann_energy_cost_saving'] = round(p['ann_energy_cost_saving'].mean(),2)
    summ['mean_ann_metric_ton_co2e_saving'] = round(p['ann_metric_ton_co2e_saving'].mean(),3)

    summ['median_simple_payback'] = round(p['simple_payback'].median(),3)
    
    p['simple_payback'] = p['simple_payback'].replace([np.inf, -np.inf], np.nan) # for mean calc
    summ['pct_pos_simple_payback_actual'] = round(len(p[p['simple_payback']>=0])/len(p)*100, 3)
    summ['mean_pos_simple_payback_actual'] = round(p.loc[p['simple_payback']>=0, 'simple_payback'].mean(),3)

    # filter: min 1 cent energy cost savings **
    min_energy_cost_saving = 0.1 # <----- **
    summ['pct_pos_simple_payback_filtered'] = round(len(
        p[(p['simple_payback']>=0) & (p['ann_energy_cost_saving']>=min_energy_cost_saving)]
    )/len(p)*100, 3)
    summ['mean_pos_simple_payback_filtered'] = round(
        p.loc[(p['simple_payback']>=0) & (p['ann_energy_cost_saving']>=min_energy_cost_saving), 
           'simple_payback'].mean(),3)

    summary_upgrades.append(summ)
    
summary_upgrades = pd.concat(summary_upgrades).reset_index(drop=True)
summary_upgrades

>>> cookcnty_packages_paper_all has 10 packages
Natural gas rate multiplier: 1

Package 1
min      -205561.309475
median        16.320408
max        27261.812241
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=1 has 844 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=1 has 621 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=1 has 639 carbon saving<0

Package 2
min      -9.264453e+05
median   -1.254389e+01
max       1.172194e+06
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=2 has 5171 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=2 has 21448 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=2 has 13615 carbon saving<0

Package 3
min      -325583.729049
median        64.219868
max       283786.499367
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=3 has 12165 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=3 has 5901 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=3 has 2374 carbon saving<0

Package 4
min      -124644.578176
median        21.660809
max        27261.812995
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=4 has 859 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=4 has 281 simple_payback<0 (due to negative energy cost saving)
       *EUI - inf* upgrade=4 has 478 pct_delta_gas_eui=INF (due to fuel introduction from upgrade)
    *CARBON - negative*  upgrade=4 has 639 carbon saving<0

Package 5
min       -17203.746695
median        46.372734
max       129725.891490
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=5 has 3015 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=5 has 75 simple_payback<0 (due to negative energy cost saving)
       *EUI - inf* upgrade=5 has 478 pct_delta_gas_eui=INF (due to fuel introduction from upgrade)
    *CARBON - negative*  upgrade=5 has 408 carbon saving<0

Package 6
min      -124644.578176
median       -11.178274
max       489734.337700
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=6 has 2158 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=6 has 26402 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=6 has 30555 carbon saving<0

Package 7
min      -60381.906228
median       20.914942
max       79188.222775
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=7 has 1856 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=7 has 3215 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=7 has 20573 carbon saving<0

Package 8
min      -3.267536e+06
median    3.427234e+01
max       3.114508e+05
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=8 has 3024 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=8 has 2146 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=8 has 14448 carbon saving<0

Package 9
min       -9096.506708
median       45.813782
max       10199.970731
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=9 has 1878 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=9 has 28 simple_payback<0 (due to negative energy cost saving)
       *EUI - inf* upgrade=9 has 534 pct_delta_gas_eui=INF (due to fuel introduction from upgrade)
    *CARBON - negative*  upgrade=9 has 291 carbon saving<0

Package 10
min      -36698.635994
median       33.964845
max       73390.558539
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=10 has 1033 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=10 has 626 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=10 has 2659 carbon saving<0

,upgrade_no,upgrade_name,n_applied,n_success,n_fail,pct_success,mean_ann_therm_gas_saving,mean_ann_kwh_elec_saving,mean_ann_mbtu_site_energy_saving,mean_pct_delta_gas_eui,...,mean_pct_delta_site_eui,mean_upgrade_cost,mean_ann_kbtu_saved_per_dollar,mean_ann_energy_cost_saving,mean_ann_metric_ton_co2e_saving,median_simple_payback,pct_pos_simple_payback_actual,mean_pos_simple_payback_actual,pct_pos_simple_payback_filtered,mean_pos_simple_payback_filtered
0,1.0,Utility Basic (Basic Shell),39976.0,39975.0,0.0,99.997,179.313,1012.089,21.585,-14.676,...,-14.122,3672.92,5.387,233.06,1.799,16.320,98.447,29.707,98.442,29.246
1,2.0,HP HVAC with Basic Shell,39974.0,39974.0,0.0,100.000,744.624,-3293.173,64.097,-69.712,...,-45.818,9252.30,6.370,24.75,1.214,-12.544,46.345,415.272,46.320,224.094
2,3.0,HP HVAC with Premium Shell,39974.0,39974.0,0.0,100.000,744.420,-948.367,72.077,-69.711,...,-52.196,21106.89,3.314,318.11,3.170,64.220,85.238,254.006,85.230,232.754
3,4.0,Utility Plus,39976.0,39976.0,0.0,100.000,325.127,1086.375,37.092,-28.765,...,-25.979,6597.52,5.269,334.03,2.637,21.661,99.297,30.985,99.295,30.869
4,5.0,Utility Deep Efficiency,39976.0,39976.0,0.0,100.000,386.472,1345.657,44.146,-36.856,...,-31.929,16471.34,2.487,404.43,3.180,46.373,99.812,65.113,99.810,61.863
5,6.0,Electrification Basic,39976.0,39976.0,0.0,100.000,780.502,-10914.698,41.701,-83.026,...,-29.787,7426.12,5.436,-293.41,-4.957,-11.178,33.955,211.628,33.940,122.761
6,7.0,Electrification with HP,39974.0,39974.0,0.0,100.000,933.689,-5245.728,76.597,-98.320,...,-57.749,12343.58,5.822,539.82,0.590,20.915,91.957,51.025,91.957,51.025
7,8.0,Electrification with HP Deep Efficiency,39974.0,39974.0,0.0,100.000,933.689,-4372.737,79.576,-98.320,...,-60.428,22885.55,3.304,633.46,1.319,34.272,94.632,80.292,94.629,72.061
8,9.0,Full Upgrade (No Electrification),39976.0,39976.0,0.0,100.000,536.760,2856.627,64.397,-51.315,...,-48.850,25824.30,2.447,670.98,5.241,45.814,99.930,52.200,99.930,52.200
9,10.0,Full Upgrade (Electrification),39976.0,39976.0,0.0,100.000,933.678,-1960.182,87.806,-98.320,...,-66.552,30210.93,2.808,892.23,3.333,33.965,98.434,49.797,98.434,49.797

In [20]:
### export UPGRADE summary
summary_upgrades.to_csv(os.path.join(result_path,'processed results',f'upgrades_summary{fn_ext}.csv'), index=False)
print(f'UPGRADE summary table saved to:\n  {os.path.join(result_path, "processed results")}')

UPGRADE summary table saved to:
  /Users/lliu2/Documents/Chicago retrofits/ResStock results/cookcnty_packages_paper_all/processed results

In [ ]:
### optional - export specific upgrade parquet as csv
save_to_csv = False # <-----
upgrade_list = range(1, 2+1) # [8] # <----- list of upgrades to convert to csv

if save_to_csv:
    for n in upgrade_list:
        p = pd.read_parquet(os.path.join(result_path,'upgrades',
                                         f'upgrade={n}/results_up{n:02d}.parquet'))
        p.to_csv(os.path.join(result_path,'upgrades',
                                         f'upgrade={n}/results_up{n:02d}.csv'), index=False)
        print(f'upgrade {n:02d} parquet file exported as csv')

### *Combine results by building prototypes from Elevate Energy into database

In [23]:
# (1) combine baseline results by non-split-level prototypes (N=12)
print(f'Natural gas rate multiplier: {NG_rate_multiplier}')
### add totals metrics:
res = get_annual_totals(res)
res['apply_upgrade.upgrade_name'] = 'Baseline'

## Load prototype csv
groups = pd.read_csv(os.path.join(result_dir,'Groups.csv'))
print('prototypes loaded')

res_proto_upgrades = []
for i, row in groups.iterrows():
    if row['HousingGroupName'] not in \
        ['Masonry All Years Split Level','Frame Post-1978 Split Level','Frame Pre-1942 Split Level']:
        res_group_i = get_res_by_prototype(res, res, row) # <----
        
        ## add tags
#         res_group_i['build_existing_model.sample_weight'] = row['Chicago Prevalence']*100/len(res_group_i)
        res_group_i['package_no'] = 0
        res_group_i['HousingGroupNo'] = row['HousingGroupNo']
        res_group_i['HousingGroupName'] = row['HousingGroupName']

        res_proto_upgrades.append(res_group_i)

res_proto_upgrades = pd.concat(res_proto_upgrades, axis=0).reset_index(drop=True)
print(f'SFD: {len(res_proto_upgrades)}')
res_others = res.loc[(res['completed_status']=='Success') &
            (res['build_existing_model.geometry_building_type_recs']!='Single-Family Detached')
           ].reset_index(drop=True)
print(f'Others: {len(res_others)}')
res_proto_upgrades = pd.concat([
    res_proto_upgrades,
    res_others], axis=0).sort_values(by=['building_id']).reset_index(drop=True)

display(res_proto_upgrades)

Natural gas rate multiplier: 1
prototypes loaded
SFD: 16753
Others: 23223

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,build_existing_model.ahs_region,build_existing_model.applicable,...,elec_CO2_rate,ann_gas_cost,ann_elec_cost,ann_energy_cost,ann_metric_ton_co2e_gas,ann_metric_ton_co2e_elec,ann_metric_ton_co2e,package_no,HousingGroupNo,HousingGroupName
0,1,53,2021-08-07 03:41:05,2021-08-07 03:42:31,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1170.500794,1418.787994,2589.288787,5.409696,8.250203,13.659900,0.0,4.0,Masonry 1942-1978 Less than 2 Stories
1,2,215,2021-08-07 00:27:52,2021-08-07 00:29:20,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1499.698017,1542.958334,3042.656351,8.251516,9.071437,17.322954,NaN,NaN,NaN
2,3,163,2021-08-07 11:04:20,2021-08-07 11:05:56,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1475.980918,1437.317917,2913.298834,8.046777,8.372756,16.419532,0.0,3.0,Masonry Post-1978 2 or more stories
3,4,64,2021-08-07 00:51:31,2021-08-07 01:06:52,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,861.453702,885.932849,1747.386551,2.741824,4.726021,7.467845,NaN,NaN,NaN
4,5,95,2021-08-07 08:43:53,2021-08-07 08:45:16,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1248.847687,1083.378671,2332.226358,6.086032,6.031883,12.117915,0.0,10.0,Frame Post-1978 2 or more stories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39971,39996,196,2021-08-07 08:04:35,2021-08-07 08:06:03,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1963.129471,1189.015267,3152.144738,12.252123,6.730539,18.982662,0.0,7.0,Masonry Pre-1942 2 or more stories
39972,39997,43,2021-08-07 08:43:16,2021-08-07 08:44:45,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1441.805930,1115.910587,2557.716517,7.751758,6.247041,13.998800,NaN,NaN,NaN
39973,39998,125,2021-08-07 06:17:39,2021-08-07 07:08:00,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,673.886772,579.648063,1253.534835,1.122639,2.700324,3.822962,NaN,NaN,NaN
39974,39999,17,2021-08-07 09:33:56,2021-08-07 09:35:37,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,2790.898293,2335.013809,5125.912102,19.397900,14.309911,33.707811,0.0,7.0,Masonry Pre-1942 2 or more stories
39975,40000,139,2021-08-07 09:58:38,2021-08-07 10:00:13,Success,None,Baseline,,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,...,0.000835,1204.864145,1469.628379,2674.492524,5.706341,8.586450,14.292791,0.0,4.0,Masonry 1942-1978 Less than 2 Stories

In [24]:
# (2) combine upgrade results by non-split-level prototypes (N=12)
print(f'Natural gas rate multiplier: {NG_rate_multiplier}')

all_proto_upgrades = []

N_upgrades = 10 # <---
package_list = list(range(1,11))
for n in package_list:
    p = pd.read_parquet(os.path.join(result_path, 'upgrades', f'upgrade={n}',
                                     f'results_up{n:02d}.parquet'))
    print(f'\nPackage {n}')

    ### get sim output at unit level
    p = get_per_unit_sim_output_limited(p, res)

    ### assign utility rates
    p = assign_utility_rates_to_upgrade(n, p, res, HVAC_upgrades_rate_change, for_packages=True)

    ### collapse upgrade cost and lifetime cols
    p = combine_upgrade_cost_and_lifetime(p)

    ### add totals metrics:
    p = get_annual_totals(p)

    ### check if upgrade has 0 successful sims
    if len(p[p['completed_status']=='Success']) == 0:
        print(f' * upgrade={n} has 0 successful simulations')

    ### calculate metrics
    p = add_sqft_eui(p, res)
    EUIi = ['gas_eui_thermpersqft','elec_eui_kwhpersqft','site_eui_kbtupersqft']
    EUIo = ['gas_eui','elec_eui','site_eui']
    for vari, varo in zip(EUIi, EUIo):
        p[f'pct_delta_{varo}'] = ((p[vari]-res[vari])/res[vari]*100)

    # annual energy saving:
    p = get_annual_gas_elec_site_energy_saving(p, res)

    # annual energy cost saving:
    p = get_annual_energy_cost_saving(p, res)
    
    # annual kBtu saved per upgrade cost:
    p['ann_kbtu_saved_per_dollar'] = p['ann_mbtu_site_energy_saving'].divide(
                            p['upgrade_cost'], axis=0)*1000

    # simple payback
    p['simple_payback'] = p['upgrade_cost']/p['ann_energy_cost_saving']

    # annual metric ton carbon emission savings:
    p = get_annual_metric_ton_co2e_saving(p, res)

    ### check for neg/large paybacks, inf eui, neg carbon savings 
    print_metrics_report(p, has_comparative_payback=False)

    ### subset to only those that have been applied with the upgrades successfully:
    upgrade_name = p['apply_upgrade.upgrade_name'].replace('',np.nan).dropna(axis=0).unique()[0]
    p = p[p['apply_upgrade.applicable']==True].reset_index(drop=True)
    p['package_no'] = n
    
    
    ### get results by prototype
    for i, row in groups.iterrows():
        if row['HousingGroupName'] not in \
        ['Masonry All Years Split Level','Frame Post-1978 Split Level','Frame Pre-1942 Split Level']:
            pi = get_res_by_prototype(p, res, row) # <----

            ### subset to only those that have been applied with the upgrades successfully:
            pi = pi[pi['simulation_output_report.applicable']==True].reset_index(drop=True)

            pi['HousingGroupNo'] = row["HousingGroupNo"]
            pi['HousingGroupName'] = row["HousingGroupName"]
            all_proto_upgrades.append(pi)
        
    ### get results by all others
    p_others = p.loc[
        (p['completed_status']=='Success') &
        (res['build_existing_model.geometry_building_type_recs']!='Single-Family Detached')
           ].reset_index(drop=True)
    all_proto_upgrades.append(p_others)

all_proto_upgrades = pd.concat(all_proto_upgrades, axis=0).sort_values(by=['building_id']).reset_index(drop=True)

aa = all_proto_upgrades.copy()
aa['build_existing_model.geometry_building_type_recs'] = aa['building_id'].map(
    res.set_index('building_id')['build_existing_model.geometry_building_type_recs'])

print('\n# of upgrades by building types:')
print(
    res.groupby(['apply_upgrade.upgrade_name',
                   'build_existing_model.geometry_building_type_recs'])['building_id'].count()
)
print(
    aa.groupby(['package_no',
                'apply_upgrade.upgrade_name',
                'build_existing_model.geometry_building_type_recs'])['building_id'].count()
)
all_proto_upgrades

Natural gas rate multiplier: 1

Package 1
min      -205561.309475
median        16.320408
max        27261.812241
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=1 has 844 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=1 has 621 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=1 has 639 carbon saving<0

Package 2
min      -9.264453e+05
median   -1.254389e+01
max       1.172194e+06
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=2 has 5171 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=2 has 21448 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=2 has 13615 carbon saving<0

Package 3
min      -325583.729049
median        64.219868
max       283786.499367
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=3 has 12165 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=3 has 5901 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=3 has 2374 carbon saving<0

Package 4
min      -124644.578176
median        21.660809
max        27261.812995
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=4 has 859 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=4 has 281 simple_payback<0 (due to negative energy cost saving)
       *EUI - inf* upgrade=4 has 478 pct_delta_gas_eui=INF (due to fuel introduction from upgrade)
    *CARBON - negative*  upgrade=4 has 639 carbon saving<0

Package 5
min       -17203.746695
median        46.372734
max       129725.891490
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=5 has 3015 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=5 has 75 simple_payback<0 (due to negative energy cost saving)
       *EUI - inf* upgrade=5 has 478 pct_delta_gas_eui=INF (due to fuel introduction from upgrade)
    *CARBON - negative*  upgrade=5 has 408 carbon saving<0

Package 6
min      -124644.578176
median       -11.178274
max       489734.337700
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=6 has 2158 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=6 has 26402 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=6 has 30555 carbon saving<0

Package 7
min      -60381.906228
median       20.914942
max       79188.222775
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=7 has 1856 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=7 has 3215 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=7 has 20573 carbon saving<0

Package 8
min      -3.267536e+06
median    3.427234e+01
max       3.114508e+05
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=8 has 3024 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=8 has 2146 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=8 has 14448 carbon saving<0

Package 9
min       -9096.506708
median       45.813782
max       10199.970731
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=9 has 1878 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=9 has 28 simple_payback<0 (due to negative energy cost saving)
       *EUI - inf* upgrade=9 has 534 pct_delta_gas_eui=INF (due to fuel introduction from upgrade)
    *CARBON - negative*  upgrade=9 has 291 carbon saving<0

Package 10
min      -36698.635994
median       33.964845
max       73390.558539
Name: simple_payback, dtype: float64
    *PAYBACK1 - too large* upgrade=10 has 1033 simple_payback>100 (including 0 INF)
    *PAYBACK1 - negative*  upgrade=10 has 626 simple_payback<0 (due to negative energy cost saving)
    *CARBON - negative*  upgrade=10 has 2659 carbon saving<0

# of upgrades by building types:
apply_upgrade.upgrade_name  build_existing_model.geometry_building_type_recs
Baseline                    Mobile Home                                           285
                            Multi-Family with 2 - 4 Units                        7712
                            Multi-Family with 5+ Units                          13047
                            Single-Family Attached                               2179
                            Single-Family Detached                              16753
Name: building_id, dtype: int64
package_no  apply_upgrade.upgrade_name               build_existing_model.geometry_building_type_recs
1           Utility Basic (Basic Shell)              Mobile Home                                           175
                                                     Multi-Family with 2 - 4 Units                        4523
                                                     Multi-Family with 5+ Units                           7756
                                                     Single-Family Attached                               1314
                                                     Single-Family Detached                              26221
2           HP HVAC with Basic Shell                 Mobile Home                                           167
                                                     Multi-Family with 2 - 4 Units                        4546
                                                     Multi-Family with 5+ Units                           7716
                                                     Single-Family Attached                               1274
                                                     Single-Family Detached                              26285
3           HP HVAC with Premium Shell               Mobile Home                                           167
                                                     Multi-Family with 2 - 4 Units                        4546
                                                     Multi-Family with 5+ Units                           7716
                                                     Single-Family Attached                               1274
                                                     Single-Family Detached                              26285
4           Utility Plus                             Mobile Home                                           175
                                                     Multi-Family with 2 - 4 Units                        4523
                                                     Multi-Family with 5+ Units                           7756
                                                     Single-Family Attached                               1314
                                                     Single-Family Detached                              26221
5           Utility Deep Efficiency                  Mobile Home                                           175
                                                     Multi-Family with 2 - 4 Units                        4523
                                                     Multi-Family with 5+ Units                           7756
                                                     Single-Family Attached                               1314
                                                     Single-Family Detached                              26221
6           Electrification Basic                    Mobile Home                                           175
                                                     Multi-Family with 2 - 4 Units                        4523
                                                     Multi-Family with 5+ Units                           7756
                                                     Single-Family Attached                               1314
                                                     Single-Family Detached                              26221
7           Electrification with HP                  Mobile Home                                           167
                                                     Multi-Family with 2 - 4 Units                        4546
                                                     Multi-Family with 5+ Units                           7716
                                                     Single-Family Attached                               1274
                                                     Single-Family Detached                              26285
8           Electrification with HP Deep Efficiency  Mobile Home                                           167
                                                     Multi-Family with 2 - 4 Units                        4546
                                                     Multi-Family with 5+ Units                           7716
                                                     Single-Family Attached                               1274
                                                     Single-Family Detached                              26285
9           Full Upgrade (No Electrification)        Mobile Home                                           175
                                                     Multi-Family with 2 - 4 Units                        4523
                                                     Multi-Family with 5+ Units                           7756
                                                     Single-Family Attached                               1314
                                                     Single-Family Detached                              26221
10          Full Upgrade (Electrification)           Mobile Home                                           175
                                                     Multi-Family with 2 - 4 Units                        4523
                                                     Multi-Family with 5+ Units                           7756
                                                     Single-Family Attached                               1314
                                                     Single-Family Detached                              26221
Name: building_id, dtype: int64

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,simulation_output_report.applicable,simulation_output_report.door_area_ft_2,...,ann_elec_cost_saving,ann_energy_cost_saving,ann_kbtu_saved_per_dollar,simple_payback,ann_metric_ton_co2e_saving_gas,ann_metric_ton_co2e_saving_elec,ann_metric_ton_co2e_saving,package_no,HousingGroupNo,HousingGroupName
0,1,44,2021-08-07 10:12:15,2021-08-07 10:20:33,Success,True,Full Upgrade (Electrification),,True,20.0,...,-157.950106,1012.550688,3.489277,25.809246,5.409696,-2.554240,2.855456,10,4.0,Masonry 1942-1978 Less than 2 Stories
1,1,144,2021-08-07 06:21:27,2021-08-07 06:28:44,Success,True,Electrification with HP Deep Efficiency,,True,20.0,...,-451.794758,718.706036,4.126118,27.596958,5.409696,-4.841023,0.568673,8,4.0,Masonry 1942-1978 Less than 2 Stories
2,1,123,2021-08-07 09:25:10,2021-08-07 09:30:18,Success,True,HP HVAC with Premium Shell,,True,20.0,...,-46.805465,352.741912,4.270289,42.176049,3.449123,-0.309561,3.139562,3,4.0,Masonry 1942-1978 Less than 2 Stories
3,1,88,2021-08-07 10:07:10,2021-08-07 10:11:35,Success,True,HP HVAC with Basic Shell,,True,20.0,...,-338.298362,63.468682,6.772666,130.299067,3.468284,-2.237428,1.230856,2,4.0,Masonry 1942-1978 Less than 2 Stories
4,1,92,2021-08-06 23:51:08,2021-08-06 23:54:31,Success,True,Utility Basic (Basic Shell),,True,20.0,...,94.597701,150.476082,4.026997,19.175140,0.482374,0.625648,1.108022,1,4.0,Masonry 1942-1978 Less than 2 Stories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399881,40000,134,2021-08-07 02:09:59,2021-08-07 02:15:27,Success,True,Electrification with HP,,True,20.0,...,-737.249742,467.614403,5.215212,32.019672,5.706341,-7.121923,-1.415582,7,4.0,Masonry 1942-1978 Less than 2 Stories
399882,40000,35,2021-08-07 00:12:14,2021-08-07 00:19:34,Success,True,Electrification with HP Deep Efficiency,,True,20.0,...,-643.254885,561.609260,3.323071,43.443336,5.706341,-6.390428,-0.684088,8,4.0,Masonry 1942-1978 Less than 2 Stories
399883,40000,177,2021-08-07 08:45:09,2021-08-07 08:52:57,Success,True,Full Upgrade (No Electrification),,True,20.0,...,389.540890,806.777985,2.681428,36.146388,3.601831,2.576334,6.178165,9,4.0,Masonry 1942-1978 Less than 2 Stories
399884,40000,226,2021-08-07 11:23:04,2021-08-07 11:28:22,Success,True,HP HVAC with Premium Shell,,True,20.0,...,-101.707257,426.230076,3.701595,52.523018,4.557459,-0.672669,3.884790,3,4.0,Masonry 1942-1978 Less than 2 Stories
399885,40000,120,2021-08-07 07:12:00,2021-08-07 07:17:48,Success,True,Utility Deep Efficiency,,True,20.0,...,220.198230,436.830047,2.128636,44.184506,1.870090,1.456341,3.326431,5,4.0,Masonry 1942-1978 Less than 2 Stories

In [25]:
# (3) combine upgrade and baseline (results by non-split-level prototypes (N=12))
cols = set(res_proto_upgrades.columns).intersection(set(all_proto_upgrades.columns))
all_proto_upgrades = pd.concat([all_proto_upgrades, res_proto_upgrades[cols]], axis=0).reset_index(drop=True)

# (4) save
print('"all_proto_upgrades" df saved')
all_proto_upgrades.to_csv(
    os.path.join(result_path,'processed results',f'upgrades_dB{fn_ext}.csv'), index=False)

display(all_proto_upgrades)

"all_proto_upgrades" df saved

,building_id,job_id,started_at,completed_at,completed_status,apply_upgrade.applicable,apply_upgrade.upgrade_name,apply_upgrade.reference_scenario,simulation_output_report.applicable,simulation_output_report.door_area_ft_2,...,ann_elec_cost_saving,ann_energy_cost_saving,ann_kbtu_saved_per_dollar,simple_payback,ann_metric_ton_co2e_saving_gas,ann_metric_ton_co2e_saving_elec,ann_metric_ton_co2e_saving,package_no,HousingGroupNo,HousingGroupName
0,1,44,2021-08-07 10:12:15,2021-08-07 10:20:33,Success,True,Full Upgrade (Electrification),,True,20.000000,...,-157.950106,1012.550688,3.489277,25.809246,5.409696,-2.554240,2.855456,10.0,4.0,Masonry 1942-1978 Less than 2 Stories
1,1,144,2021-08-07 06:21:27,2021-08-07 06:28:44,Success,True,Electrification with HP Deep Efficiency,,True,20.000000,...,-451.794758,718.706036,4.126118,27.596958,5.409696,-4.841023,0.568673,8.0,4.0,Masonry 1942-1978 Less than 2 Stories
2,1,123,2021-08-07 09:25:10,2021-08-07 09:30:18,Success,True,HP HVAC with Premium Shell,,True,20.000000,...,-46.805465,352.741912,4.270289,42.176049,3.449123,-0.309561,3.139562,3.0,4.0,Masonry 1942-1978 Less than 2 Stories
3,1,88,2021-08-07 10:07:10,2021-08-07 10:11:35,Success,True,HP HVAC with Basic Shell,,True,20.000000,...,-338.298362,63.468682,6.772666,130.299067,3.468284,-2.237428,1.230856,2.0,4.0,Masonry 1942-1978 Less than 2 Stories
4,1,92,2021-08-06 23:51:08,2021-08-06 23:54:31,Success,True,Utility Basic (Basic Shell),,True,20.000000,...,94.597701,150.476082,4.026997,19.175140,0.482374,0.625648,1.108022,1.0,4.0,Masonry 1942-1978 Less than 2 Stories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439857,39996,196,2021-08-07 08:04:35,2021-08-07 08:06:03,Success,None,Baseline,,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,Masonry Pre-1942 2 or more stories
439858,39997,43,2021-08-07 08:43:16,2021-08-07 08:44:45,Success,None,Baseline,,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439859,39998,125,2021-08-07 06:17:39,2021-08-07 07:08:00,Success,None,Baseline,,True,6.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439860,39999,17,2021-08-07 09:33:56,2021-08-07 09:35:37,Success,None,Baseline,,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,Masonry Pre-1942 2 or more stories
439861,40000,139,2021-08-07 09:58:38,2021-08-07 10:00:13,Success,None,Baseline,,True,20.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4.0,Masonry 1942-1978 Less than 2 Stories

In [26]:
## save metadata for dB
if NG_rate_multiplier==1:
    cols2 = sorted((set(res_proto_upgrades.columns)-set(cols)).union(
                   set(['building_id','completed_status',
                        'package_no','HousingGroupNo','HousingGroupName']))
                  )
    res_proto_meta = res_proto_upgrades[cols2]
    res_proto_meta = res_proto_meta[res_proto_meta['completed_status']=='Success'].reset_index(drop=True)
    
    cols_to_drop = [x for x in res_proto_meta.columns if 
                    x.startswith('simulation_output_report.option') or
                    x == 'simulation_output_report.upgrade_cost_usd']
    
    res_proto_meta = res_proto_meta.drop(cols_to_drop, axis=1)

    res_proto_meta.to_csv(
        os.path.join(result_path,'processed results',f'upgrades_dB_meta{fn_ext}.csv'), index=False)

    print('"res_proto_meta" df saved')
    display(res_proto_meta)

"res_proto_meta" df saved

,HousingGroupName,HousingGroupNo,build_existing_model.ahs_region,build_existing_model.applicable,build_existing_model.ashrae_iecc_climate_zone_2004,build_existing_model.bathroom_spot_vent_hour,build_existing_model.bedrooms,build_existing_model.building_america_climate_zone,build_existing_model.ceiling_fan,build_existing_model.census_division,...,build_existing_model.usage_level,build_existing_model.vacancy_status,build_existing_model.vintage,build_existing_model.vintage_acs,build_existing_model.water_heater,build_existing_model.window_areas,build_existing_model.windows,building_id,completed_status,package_no
0,Masonry 1942-1978 Less than 2 Stories,4.0,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour20,4,Cold,Standard Efficiency,East North Central,...,Medium,Occupied,1950s,1940-59,Gas Standard,F9 B9 L9 R9,2+ Pane,1,Success,0.0
1,NaN,NaN,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour14,3,Cold,Standard Efficiency,East North Central,...,High,Occupied,1940s,1940-59,Gas Standard,F12 B12 L12 R12,2+ Pane,2,Success,NaN
2,Masonry Post-1978 2 or more stories,3.0,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour5,3,Cold,Standard Efficiency,East North Central,...,Low,Occupied,1980s,1980-99,Gas Standard,F30 B30 L30 R30,2+ Pane,3,Success,0.0
3,NaN,NaN,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour7,2,Cold,Standard Efficiency,East North Central,...,Low,Occupied,1950s,1940-59,Gas Standard,F30 B30 L30 R30,2+ Pane,4,Success,NaN
4,Frame Post-1978 2 or more stories,10.0,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour7,5,Cold,Standard Efficiency,East North Central,...,Low,Occupied,1980s,1980-99,Gas Standard,F9 B9 L9 R9,2+ Pane,5,Success,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39971,Masonry Pre-1942 2 or more stories,7.0,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour6,3,Cold,None,East North Central,...,Low,Occupied,<1940,<1940,Gas Standard,F12 B12 L12 R12,2+ Pane,39996,Success,0.0
39972,NaN,NaN,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour2,2,Cold,Standard Efficiency,East North Central,...,Medium,Occupied,1970s,1960-79,Gas Standard,F30 B30 L30 R30,1 Pane,39997,Success,NaN
39973,NaN,NaN,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour7,1,Cold,Standard Efficiency,East North Central,...,Low,Occupied,1990s,1980-99,Gas Standard,F12 B12 L12 R12,1 Pane,39998,Success,NaN
39974,Masonry Pre-1942 2 or more stories,7.0,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour10,5,Cold,None,East North Central,...,Low,Occupied,<1940,<1940,Gas Standard,F12 B12 L12 R12,2+ Pane,39999,Success,0.0
39975,Masonry 1942-1978 Less than 2 Stories,4.0,"CBSA Chicago-Naperville-Elgin, IL-IN-WI",True,5A,Hour20,4,Cold,None,East North Central,...,Low,Occupied,1950s,1940-59,Gas Standard,F9 B9 L9 R9,2+ Pane,40000,Success,0.0

### 2.2. Get PACKAGE results by building prototypes from Elevate Energy

In [ ]:
combine_all_upgrades_and_export_as_csv = True # <------ used to plot distributions

#### count upgrades
N_upgrades = 10 # <---

print(f'Natural gas rate multiplier: {NG_rate_multiplier}')
## (1) Load prototype csv
groups2 = pd.read_csv(os.path.join(result_dir,'Groups.csv'))
groups2 = groups2.drop(['Non-normalized gas usage','Non-normalized elec. usage'], axis=1)
chars_to_map = groups2[['HousingGroupNo','HousingGroupName','Stories','WallType','Vintage']]
print('prototypes loaded.')

Metric_map1 = {'count': '',
               'mean_gas_eui therm_per_sqft': 'gas_eui_thermpersqft',
               'mean_elec_eui kwh_per_sqft': 'elec_eui_kwhpersqft',
               'mean_site_eui kbtu_per_sqft': 'site_eui_kbtupersqft'
              }

### (2) get baseline results
for i, row in chars_to_map.iterrows():
    res_i = get_res_by_prototype(res, res, row) # <----
    
    for metric, res_var in Metric_map1.items():
        if metric == 'count':
            groups2.loc[i, 'count'] = len(res_i)
        else:
            groups2.loc[i, metric] = res_i[res_var].mean()

groups2.columns = pd.MultiIndex.from_product([['Baseline'], groups2.columns])
print('Prototype baseline results copied.')
print(f'Number of buildings simulated: {len(res)}')
N_baseline = len(groups2.columns)

if combine_all_upgrades_and_export_as_csv:
    all_proto_upgrades = []

### (3) add upgrades results
package_list = list(range(1, 1+N_upgrades))
for n in package_list:
    nf = f'0{n}' if n<10 else n
    p = pd.read_parquet(os.path.join(result_path, 'upgrades', f'upgrade={n}',
                                     f'results_up{n:02d}.parquet'))
    print(f'\nPackage {n}')
    
    ### get sim output at unit level
    p = get_per_unit_sim_output_limited(p, res)

    ### assign utility rates
    p = assign_utility_rates_to_upgrade(n, p, res, HVAC_upgrades_rate_change, for_packages=True)
    
    ### collapse upgrade cost and lifetime cols
    p = combine_upgrade_cost_and_lifetime(p)

    ### check if upgrade has 0 successful sims
    if len(p[p['completed_status']=='Success']) == 0:
        print(f' * upgrade={n} has 0 successful simulations')

    ### calculate metrics
    p = add_sqft_eui(p, res)
    EUIi = ['gas_eui_thermpersqft','elec_eui_kwhpersqft','site_eui_kbtupersqft']
    EUIo = ['gas_eui','elec_eui','site_eui']
    for vari, varo in zip(EUIi, EUIo):
        p[f'pct_delta_{varo}'] = ((p[vari]-res[vari])/res[vari]*100)


    # annual energy saving:
    p = get_annual_gas_elec_site_energy_saving(p, res)

    # annual energy cost saving:
    p = get_annual_energy_cost_saving(p, res)
    
    # annual kBtu saved per upgrade cost:
    p['ann_kbtu_saved_per_dollar'] = p['ann_mbtu_site_energy_saving'].divide(
                            p['upgrade_cost'], axis=0)*1000

    # simple payback
    p['simple_payback'] = p['upgrade_cost']/p['ann_energy_cost_saving']

    # annual metric ton carbon emission savings:
    p = get_annual_metric_ton_co2e_saving(p, res)

    ### check for neg/large paybacks, inf eui, neg carbon savings 
    print_metrics_report(p, has_comparative_payback=False)
    
    ### subset to only those that have been applied with the upgrades successfully:
    upgrade_name = p['apply_upgrade.upgrade_name'].replace('',np.nan).dropna(axis=0).unique()[0]
    p = p[p['apply_upgrade.applicable']==True].reset_index(drop=True)
    p['package_no'] = n
    
    ### get results by prototype
    for i, row in chars_to_map.iterrows():
        pi = get_res_by_prototype(p, res, row) # <----
        
        ### subset to only those that have been applied with the upgrades successfully:
        pi = pi[pi['simulation_output_report.applicable']==True].reset_index(drop=True)
        
        if combine_all_upgrades_and_export_as_csv:
            pi['HousingGroupNo'] = row["HousingGroupNo"]
            pi['HousingGroupName'] = row["HousingGroupName"]
            all_proto_upgrades.append(pi)
        
        for var in ['pct_delta_gas_eui','pct_delta_elec_eui','pct_delta_site_eui','ann_metric_ton_co2e_saving']:
            pi[var] = pi[var].replace([np.inf, -np.inf], np.nan) # for mean calc
            groups2.loc[i, ((f'mean_{var}'),(f'pkg{nf}: {upgrade_name}'))] = round(pi[var].replace(
                [np.inf, -np.inf], np.nan).mean(), 3)
        for var in ['upgrade_cost', 'ann_kbtu_saved_per_dollar','ann_energy_cost_saving']:
            pi[var] = pi[var].replace([np.inf, -np.inf], np.nan) # for mean calc
            groups2.loc[i, ((f'mean_{var}'),(f'pkg{nf}: {upgrade_name}'))] = round(pi[var].mean(), 2)
        for var in ['simple_payback']:
            n_cp = len(pi[~pi[var].isnull()])
            if n_cp>0:
                groups2.loc[i, ((f'median_{var}'),(f'pkg{nf}: {upgrade_name}'))] = round(pi[var].median(), 2)
                pi[var] = pi[var].replace([np.inf, -np.inf], np.nan) # for mean calc
                
                # filter: min 1 cent energy cost savings **
                min_energy_cost_saving = 0.1 # <----- ** 
                groups2.loc[i, ((f'pct_pos_{var}'),(f'pkg{nf}: {upgrade_name}'))] = round(len(
                    pi[(p[var]>=0) & (pi['ann_energy_cost_saving']>=min_energy_cost_saving)]
                    )/n_cp*100, 3)
                groups2.loc[i, ((f'mean_pos_{var}'),(f'pkg{nf}: {upgrade_name}'))] = round(
                    pi.loc[(p[var]>=0) & (p['ann_energy_cost_saving']>=min_energy_cost_saving),var].mean(), 2)
            else:
                groups2.loc[i, ((f'median_{var}'),(f'pkg{nf}: {upgrade_name}'))] = np.nan
                groups2.loc[i, ((f'pct_pos_{var}'),(f'pkg{nf}: {upgrade_name}'))] = np.nan
                groups2.loc[i, ((f'mean_pos_{var}'),(f'pkg{nf}: {upgrade_name}'))] = np.nan
        
if combine_all_upgrades_and_export_as_csv:
    all_proto_upgrades = pd.concat(all_proto_upgrades).reset_index(drop=True).replace('',np.nan).dropna(axis=1, how='all')
    all_proto_upgrades.to_csv(os.path.join(result_path,'processed results',f'all_upgrades_by_prototype_combined{fn_ext}.csv'), index=False)
    print(f'\nall {len(package_list)} UPGRADEs are combined and saved to:\n  {os.path.join(result_path, "processed results")}')            

# split to sort
groups_upgrades = groups2.iloc[:, N_baseline:].sort_index(axis=1, level=[0,1]) # in upgrades section, sort by col indices
groups2 = pd.concat([groups2.iloc[:, :N_baseline],groups_upgrades], axis=1)              
groups2

In [ ]:
### export prototype UPGRADE summary
groups2.to_csv(os.path.join(result_path,'processed results',f'upgrades_prototype_results{fn_ext}.csv'), index=False)
print(f'UPGRADE summary table saved to:\n  {os.path.join(result_path, "processed results")}')

### Get baseline totals for comparison

### 2.3. Visualize UPGRADE prototype summary 
#### 2.3.1. plot mean metrics values
Run cell below to load df for plots

In [ ]:
load_df_for_plot_below_from_file = False # <-----
    
if load_df_for_plot_below_from_file:
    NG_rate_multiplier = 1 # 1 or 3 <----- This controls what to plot in both '2.3.1.' and '2.3.2.' plots
 
    if NG_rate_multiplier > 1:
        fn_ext = f'_{NG_rate_multiplier}x_gas_prices' # file name extension to add to relevant results
    else:
        fn_ext = ''
    
    groups2 = pd.read_csv(os.path.join(result_path,'processed results',f'upgrades_prototype_results{fn_ext}.csv'),
                         header=[0, 1])
    
    print(f'"groups2{fn_ext}" df loaded from file.')
    display(groups2)

In [ ]:
### other metrics to consider:
# monthly utility bills (gas + elec)
# carbon savings (require timeseries results)

zoom_in_plots = False # <-------

zoom_in_xlimits = {
    'mean_pct_delta_gas_eui': [None, None],
    'mean_pct_delta_elec_eui': [None, None],
    'mean_pct_delta_site_eui': [-25, None],
    'mean_upgrade_cost': [None, 10000],
    'mean_ann_kbtu_saved_per_dollar': [None, 500],
    'mean_ann_energy_cost_saving': [None, 2000],
    'mean_ann_metric_ton_co2e_saving': [None, 20],
    'median_simple_payback': [-70, 70],
}

# create subfolder for plots:
plot_path1 = os.path.join(plot_path, 'mean_values_by_prototype')
if not os.path.exists(plot_path1):
    os.mkdir(plot_path1)
print(f'plot dir: {plot_path1}\n')

title_ext = '' if fn_ext == '' else f' ({fn_ext.replace("_"," ").lstrip()})'

if NG_rate_multiplier == 1:
    para_labels = {
        'mean_pct_delta_gas_eui': 'Mean percent change from baseline in gas use intensity (therm/sqft)',
        'mean_pct_delta_elec_eui': 'Mean percent change from baseline in electricity use intensity (kWh/sqft)',
        'mean_pct_delta_site_eui': 'Mean percent change from baseline in site energy use intensity (kBtu/sqft)',
        'mean_upgrade_cost': 'Mean upgrade capital cost ($)',
        'mean_ann_kbtu_saved_per_dollar': 'Mean annual site energy saving per upgrade cost (kBtu/$)',
        'mean_ann_energy_cost_saving': f'Mean annual energy cost saving{title_ext} ($)',
        'mean_ann_metric_ton_co2e_saving': f'Mean annual carbon emission saving (metric ton CO₂e)',
        'median_simple_payback': f'Median simple payback period{title_ext} (yr)',
        'mean_pos_simple_payback': f'Mean positive simple payback period{title_ext} (yr)',
    }
else:
    para_labels = {
        'mean_ann_energy_cost_saving': f'Mean annual energy cost saving{title_ext} ($)',
        'median_simple_payback': f'Median simple payback period{title_ext} (yr)',
        'mean_pos_simple_payback': f'Mean positive simple payback period{title_ext} (yr)',
    }

    
for i, para_to_plot in enumerate(para_labels.keys(),1):
    
    zoom_ext = ''
    if zoom_in_plots:
        if len(list(x for x in zoom_in_xlimits[para_to_plot] if x is not None))>0:
            zoom_ext = '_zoomed'
    
    print(f'>> {i}. plotting {para_to_plot}{fn_ext}{zoom_ext}...')
    para_label = para_labels[para_to_plot]

    idx = groups2.loc[:,(('Baseline'),('HousingGroupNo'))].astype(str) +'. '+\
          groups2.loc[:,(('Baseline'),('HousingGroupName'))]
    UPi = groups2.set_index(idx)[para_to_plot]
    xmin = UPi.replace([np.inf, -np.inf], np.nan).min().min()
    xmax = UPi.replace([np.inf, -np.inf], np.nan).max().max()

    fig, ax = plt.subplots(ncols=1, nrows=1, sharex=True, sharey=True, figsize=(14, 14))

    ### Group 1: Intensive, fuel-agnostic upgrades (upg01-upg21)
    # Group 1A: (upg01-upg10) N=10
    UPi.plot(kind='barh', width=0.8, ax=ax)
    ax.xaxis.grid(True)
    if (para_to_plot[-3:]=='eui') & (xmin < -50):
        ax.axvline(x=-50, linestyle='--', color='darkred')
    ax.set_title(para_label, fontsize=15, y=1)
    handles, labels = ax.get_legend_handles_labels()
    ax.legend(handles[::-1], labels[::-1], ncol=1, loc='center left', bbox_to_anchor=(1, 0.5), fontsize='medium')
    ax.margins(y=0)
    
    if zoom_in_plots:
        [xmin, xmax] = zoom_in_xlimits[para_to_plot]
        if xmin is not None:
            ax.set_xlim(left = xmin)
        if xmax is not None:
            ax.set_xlim(right=xmax)
            
    if para_to_plot in ['median_simple_payback', 'mean_pos_simple_payback']:
        if xmax >= 150:
            ax.set_xlim(0,150)
    
    plt.tight_layout()
    
    filename = f'{iter_path}-comparison_{para_to_plot}{fn_ext}.pdf'
    fig.savefig(os.path.join(plot_path1, filename),
                bbox_inches='tight')

#### 2.3.2. plot mean values for Chicago avg per SFD

In [ ]:
Wtchicago = groups2.loc[:,[('Baseline', 'HousingGroupName'),('Baseline', 'Chicago Prevalence')]
                       ]['Baseline'].set_index('HousingGroupName')

## add 'Chicago avg' and 'Chicago total'
groups_avg = groups2.set_index(('Baseline', 'HousingGroupName')).drop('Baseline', level=0, axis=1)
groups_avg.index.name = groups_avg.index.name[1]
groups_avg = groups_avg.stack(level=0).stack().unstack(level=0)
groups_avg['Chicago avg'] = np.where(np.isnan(groups_avg),0,groups_avg).dot(
    np.where(np.isnan(Wtchicago),0,Wtchicago)) # np.dot() ignoring nan

## add upgrade names
upgrade_name_map = summary_upgrades[['upgrade_no','upgrade_name']].copy()
upgrade_name_map.loc[:,'upgrade'] = upgrade_name_map['upgrade_no'].astype(int)
# upgrade_name_map.loc[:,'upgrade'] = 'upg' + \
#     upgrade_name_map['upgrade_no'].astype(int).astype(str).str.rjust(2,'0')
upgrade_name_map = upgrade_name_map.set_index('upgrade')['upgrade_name']

groups_avg = groups_avg.reset_index().rename({'level_0':'metrics','level_1':'upgrade_no'}, axis=1)
groups_avg['upgrade_no'] = groups_avg['upgrade_no'].str[3:5].astype(int)
groups_avg['upgrade_name'] = groups_avg['upgrade_no'].map(upgrade_name_map)
groups_avg = groups_avg.set_index(['metrics','upgrade_no','upgrade_name']).sort_index().reset_index()

### save a copy
groups_avg.to_csv(os.path.join(result_path,
                               'processed results',
                               f'upgrades_prototype_chicago_avg_results{fn_ext}.csv'),
                  index=True)
print(f'Natural gas rate multiplier: {NG_rate_multiplier}')
groups_avg

In [ ]:
para_to_plot = 'Chicago avg' # <------

N_upgrades=10
upgrade_sets = {
    'Packages': range(1, N_upgrades+1),
}
upgrade_set_colors = {
    'Packages': 'tab:blue',
}

# create subfolder for plots:
plot_path2 = os.path.join(plot_path, 'mean_values_chicago_avg')
if not os.path.exists(plot_path2):
    os.mkdir(plot_path2)
print(f'plot dir: {plot_path2}\n')

if NG_rate_multiplier == 1: 
    metrics_to_plot = groups_avg['metrics'].unique()
else:
    metrics_to_plot = ['mean_ann_energy_cost_saving', 'median_simple_payback']
    
for metric in metrics_to_plot:
    title_ext = '' if fn_ext == '' else f' ({fn_ext.replace("_"," ").lstrip()})'
    title = f'{para_to_plot}: {metric}{title_ext}'
    print(f'Plotting {title}...')
    
    for n, up in enumerate(upgrade_sets.keys(),1):
        print(f'    - Group{n}')
        
        groupi = groups_avg[(groups_avg['metrics']==metric) & 
                              (groups_avg['upgrade_no'].isin(upgrade_sets[up]))][[
            'upgrade_name',para_to_plot]].set_index('upgrade_name').sort_values(by=para_to_plot)
        groupi.index.name = up
        
        ht = len(groupi)
        fig, ax = plt.subplots(figsize=(6, 0.3*ht))
        groupi.plot.barh(color=upgrade_set_colors[up], legend=False, title=title, ax=ax)
        
        # For each bar: Place a label ############################
        rects = ax.patches
        for rect in rects:
            # Get X and Y placement of label from rect.
            x_value = rect.get_width()
            y_value = rect.get_y() + rect.get_height() / 2

            # Number of points between bar and label. Change to your liking.
            space = 5
            # Vertical alignment for positive values
            ha = 'left'

            # If value of bar is negative: Place label left of bar
            if x_value < 0:
                # Invert space to place label to the left
                space *= -1
                # Horizontally align label at right
                ha = 'right'

            # Use X value as label and format number with one decimal place
            label = "{:.1f}".format(x_value)

            # Create annotation
            plt.annotate(
                label,                      # Use `label` as label
                (x_value, y_value),         # Place label at end of the bar
                xytext=(space, 0),          # Horizontally shift label by `space`
                textcoords="offset points", # Interpret `xytext` as offset in points
                va='center',                # Vertically center label
                ha=ha,                      # Horizontally align label differently for
                fontsize=8)                 # positive and negative values. 
            
        ax.margins(x=0.2)    
        ax.axvline(x=0, linestyle='-', color='gray')
        if (metric[-3:]=='eui') & (ax.get_xlim()[0] < -50):
            ax.axvline(x=-50, linestyle='--', color='darkred')
        
        filename = f'upgrades_{iteration}-{para_to_plot}_{metric}{fn_ext}.pdf'
        fig.savefig(os.path.join(plot_path2, filename),
                    bbox_inches='tight')

#### 2.3.4. plot metrics distribution
Run cell below to load df for plots

In [ ]:
load_df_for_plot_below_from_file = False # <-----

if load_df_for_plot_below_from_file:
    NG_rate_multiplier = 1 # 1 or 3 <----- This controls what to plot in both '2.3.1.' and '2.3.2.' plots
 
    if NG_rate_multiplier > 1:
        fn_ext = f'_{NG_rate_multiplier}x_gas_prices' # file name extension to add to relevant results
    else:
        fn_ext = ''

    all_proto_upgrades = pd.read_csv(os.path.join(result_path, 'processed results', 'all_upgrades_by_prototype_combined.csv'))
    
    print(f'"all_proto_upgrades{fn_ext}" df loaded from file.')
    N_upgrades = all_proto_upgrades['package_no'].unique().max()
    print(f'   total number of packages: {N_upgrades}')
    
    display(all_proto_upgrades)

In [ ]:
### other metrics to consider:
# monthly utility bills (gas + elec)
# carbon savings (require timeseries results)

# create subfolder for plots:
plot_path4 = os.path.join(plot_path, 'distribution_by_prototype')
if not os.path.exists(plot_path4):
    os.mkdir(plot_path4)
print(f'plot dir: {plot_path4}\n')

title_ext = '' if fn_ext == '' else f' ({fn_ext.replace("_"," ").lstrip()})'

## modifying payback periods, cap either ends at [100,-100] 
all_proto_upgrades.loc[(all_proto_upgrades[all_proto_upgrades['simple_payback']>100]).index,
                       'simple_payback'] = 100
all_proto_upgrades.loc[(all_proto_upgrades[all_proto_upgrades['simple_payback']<-100]).index,
                       'simple_payback'] = -100

if NG_rate_multiplier == 1:
    para_labels = {
        'pct_delta_gas_eui': 'Percent change from baseline in gas use intensity (therm/sqft)',
        'pct_delta_elec_eui': 'Percent change from baseline in electricity use intensity (kWh/sqft)',
        'pct_delta_site_eui': 'Percent change from baseline in site energy use intensity (kBtu/sqft)',
        'upgrade_cost': 'Upgrade capital cost ($)',
        'ann_kbtu_saved_per_dollar': 'Annual site energy saving per upgrade cost (kBtu/$)',
        'ann_energy_cost_saving': f'Annual site energy cost saving{title_ext}',
        'ann_metric_ton_co2e_saving': f'Annual carbon emission saving (metric ton CO₂e)',
        'simple_payback': f'Simple payback period (yr){title_ext}',
    }
else:
    para_labels = {
        'ann_energy_cost_saving': f'Annual site energy cost saving{title_ext}',
        'simple_payback': f'Simple payback period (yr){title_ext}',
    }

N_upgrades=10
cols_to_match = list(f'pkg{n:02d}' for n in range(1,N_upgrades+1))

for i, para_to_plot in enumerate(para_labels.keys(),1):
    
    print(f'>> {i}. plotting {para_to_plot}{fn_ext}...')
    xmin = all_proto_upgrades[para_to_plot].min(); xmax = all_proto_upgrades[para_to_plot].max()
    
    fig, axes = plt.subplots(ncols=15, nrows=1, sharex=True, sharey=True, figsize=(30, 6))
    for h in range(1,16):
        ax = axes[h-1]
        p = all_proto_upgrades.query('HousingGroupNo==@h')[['HousingGroupNo','HousingGroupName',
                                                            'package_no', para_to_plot]]
        lab = f'{p["HousingGroupNo"].iloc[0]}. {p["HousingGroupName"].iloc[0]}'
        lab = '\n'.join([lab[i:i+15] for i in range(0, len(lab), 15)]) # break up long string
        p.loc[:,'package_no'] = 'pkg'+p['package_no'].astype(str).str.zfill(2)
        p = p.sort_values(by='package_no')
        p = p.set_index([p.index, 'package_no'])[
            para_to_plot].unstack(level=-1).dropna(
            axis=0, how='all')
        
        ### show all upgrades
        for col in set(cols_to_match)-set(p.columns):
            p[col] = np.nan
        p = p.sort_index(axis=1).reset_index(drop=True)
    
        if para_to_plot == 'simple_payback':
            showmeans = False
        else:
            showmeans = True
            
        try:
            p.boxplot(ax=ax, vert=False, grid=False, showmeans=showmeans)
        except:
            pass

        ax.set_title(lab)
        if h==1:
            ax.set_ylabel('package')
        ax.axvline(x=0, linestyle='-.', color='gray')
        if (para_to_plot[-3:]=='eui') & (xmin < -50):
            ax.axvline(x=-50, linestyle='--', color='darkred')
            
        ax.set_yticks(range(1, 1+N_upgrades))
        ax.set_yticklabels(cols_to_match)
        
    para_label = para_labels[para_to_plot]
    fig.suptitle(para_label, fontsize=20, y=1.03)
    plt.tight_layout()
    
    filename = os.path.join(plot_path4, f'{iter_path}-distribution_{para_to_plot}{fn_ext}.pdf')
    fig.savefig(filename, bbox_inches='tight')